// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AuthToken auth token
//
// swagger:model authToken
type AuthToken struct {

	// authenticator data
	// Example: SGVsbG8gV29ybGQ=
	// Format: byte
	AuthenticatorData strfmt.Base64 `json:"authenticator_data,omitempty"`

	// client data json
	// Example: SGVsbG8gV29ybGQ=
	// Format: byte
	ClientDataJSON strfmt.Base64 `json:"client_data_json,omitempty"`

	// credential id
	// Example: cred-xyz
	CredentialID string `json:"credential_id,omitempty"`

	// member id
	// Example: user-123
	MemberID string `json:"member_id,omitempty"`

	// passkey signature
	// Example: SGVsbG8gV29ybGQ=
	// Format: byte
	PasskeySignature strfmt.Base64 `json:"passkey_signature,omitempty"`

	// public key
	// Example: pub-0x1234567890abcdef...
	// Required: true
	PublicKey *string `json:"public_key"`

	// signature
	// Example: SGVsbG8gV29ybGQ=
	// Required: true
	// Format: byte
	Signature *strfmt.Base64 `json:"signature"`
}

// Validate validates this auth token
func (m *AuthToken) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthToken) validatePublicKey(formats strfmt.Registry) error {

	if err := validate.Required("public_key", "body", m.PublicKey); err != nil {
		return err
	}

	return nil
}

func (m *AuthToken) validateSignature(formats strfmt.Registry) error {

	if err := validate.Required("signature", "body", m.Signature); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this auth token based on context it is used
func (m *AuthToken) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthToken) UnmarshalBinary(b []byte) error {
	var res AuthToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
