// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BackupStatus backup status
//
// swagger:model backupStatus
type BackupStatus struct {

	// node id
	NodeID string `json:"node_id,omitempty"`

	// recoverable
	Recoverable bool `json:"recoverable,omitempty"`

	// required shares
	RequiredShares int64 `json:"required_shares,omitempty"`

	// total shares
	TotalShares int64 `json:"total_shares,omitempty"`
}

// Validate validates this backup status
func (m *BackupStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this backup status based on context it is used
func (m *BackupStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BackupStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BackupStatus) UnmarshalBinary(b []byte) error {
	var res BackupStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
