// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BackupShare backup share
//
// swagger:model backupShare
type BackupShare struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// key id
	KeyID string `json:"key_id,omitempty"`

	// node id
	NodeID string `json:"node_id,omitempty"`

	// share index
	ShareIndex int64 `json:"share_index,omitempty"`
}

// Validate validates this backup share
func (m *BackupShare) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this backup share based on context it is used
func (m *BackupShare) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BackupShare) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BackupShare) UnmarshalBinary(b []byte) error {
	var res BackupShare
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
