// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeriveKeyResponse derive key response
//
// swagger:model deriveKeyResponse
type DeriveKeyResponse struct {

	// address
	// Example: 0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb
	Address string `json:"address,omitempty"`

	// chain code
	// Example: 0x...
	// Required: true
	ChainCode *string `json:"chain_code"`

	// chain type
	// Example: ethereum
	// Required: true
	ChainType *string `json:"chain_type"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// index
	// Example: 0
	// Required: true
	Index *int64 `json:"index"`

	// public key
	// Example: pub-0x1234567890abcdef...
	// Required: true
	PublicKey *string `json:"public_key"`

	// root key id
	// Example: key-1234567890abcdef
	// Required: true
	RootKeyID *string `json:"root_key_id"`

	// status
	// Example: Active
	// Required: true
	// Enum: [Active Inactive]
	Status *string `json:"status"`

	// tags
	Tags map[string]string `json:"tags,omitempty"`

	// wallet id
	// Example: wallet-1234567890abcdef
	// Required: true
	WalletID *string `json:"wallet_id"`
}

// Validate validates this derive key response
func (m *DeriveKeyResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChainCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIndex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRootKeyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWalletID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeriveKeyResponse) validateChainCode(formats strfmt.Registry) error {

	if err := validate.Required("chain_code", "body", m.ChainCode); err != nil {
		return err
	}

	return nil
}

func (m *DeriveKeyResponse) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	return nil
}

func (m *DeriveKeyResponse) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *DeriveKeyResponse) validateIndex(formats strfmt.Registry) error {

	if err := validate.Required("index", "body", m.Index); err != nil {
		return err
	}

	return nil
}

func (m *DeriveKeyResponse) validatePublicKey(formats strfmt.Registry) error {

	if err := validate.Required("public_key", "body", m.PublicKey); err != nil {
		return err
	}

	return nil
}

func (m *DeriveKeyResponse) validateRootKeyID(formats strfmt.Registry) error {

	if err := validate.Required("root_key_id", "body", m.RootKeyID); err != nil {
		return err
	}

	return nil
}

var deriveKeyResponseTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Active","Inactive"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deriveKeyResponseTypeStatusPropEnum = append(deriveKeyResponseTypeStatusPropEnum, v)
	}
}

const (

	// DeriveKeyResponseStatusActive captures enum value "Active"
	DeriveKeyResponseStatusActive string = "Active"

	// DeriveKeyResponseStatusInactive captures enum value "Inactive"
	DeriveKeyResponseStatusInactive string = "Inactive"
)

// prop value enum
func (m *DeriveKeyResponse) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deriveKeyResponseTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DeriveKeyResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

func (m *DeriveKeyResponse) validateWalletID(formats strfmt.Registry) error {

	if err := validate.Required("wallet_id", "body", m.WalletID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this derive key response based on context it is used
func (m *DeriveKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeriveKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeriveKeyResponse) UnmarshalBinary(b []byte) error {
	var res DeriveKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
