// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetSessionResponse get session response
//
// swagger:model getSessionResponse
type GetSessionResponse struct {

	// completed at
	// Format: date-time
	CompletedAt strfmt.DateTime `json:"completed_at,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// 执行时长（毫秒）
	DurationMs int64 `json:"duration_ms,omitempty"`

	// 错误信息（失败时）
	ErrorMessage string `json:"error_message,omitempty"`

	// progress
	Progress *GetSessionResponseProgress `json:"progress,omitempty"`

	// 公钥（DKG 完成后才有）
	// Example: 0x...
	PublicKey string `json:"public_key,omitempty"`

	// session id
	// Required: true
	// Format: uuid
	SessionID *strfmt.UUID `json:"session_id"`

	// session type
	// Example: signing
	// Enum: [dkg signing]
	SessionType string `json:"session_type,omitempty"`

	// 签名结果（完成后才有）
	// Example: 0x...
	Signature string `json:"signature,omitempty"`

	// status
	// Example: running
	// Required: true
	// Enum: [pending running completed failed]
	Status *string `json:"status"`

	// wallet id
	// Required: true
	// Format: uuid
	WalletID *strfmt.UUID `json:"wallet_id"`
}

// Validate validates this get session response
func (m *GetSessionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProgress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSessionType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWalletID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSessionResponse) validateCompletedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CompletedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("completed_at", "body", "date-time", m.CompletedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetSessionResponse) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GetSessionResponse) validateProgress(formats strfmt.Registry) error {
	if swag.IsZero(m.Progress) { // not required
		return nil
	}

	if m.Progress != nil {
		if err := m.Progress.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("progress")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("progress")
			}
			return err
		}
	}

	return nil
}

func (m *GetSessionResponse) validateSessionID(formats strfmt.Registry) error {

	if err := validate.Required("session_id", "body", m.SessionID); err != nil {
		return err
	}

	if err := validate.FormatOf("session_id", "body", "uuid", m.SessionID.String(), formats); err != nil {
		return err
	}

	return nil
}

var getSessionResponseTypeSessionTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["dkg","signing"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getSessionResponseTypeSessionTypePropEnum = append(getSessionResponseTypeSessionTypePropEnum, v)
	}
}

const (

	// GetSessionResponseSessionTypeDkg captures enum value "dkg"
	GetSessionResponseSessionTypeDkg string = "dkg"

	// GetSessionResponseSessionTypeSigning captures enum value "signing"
	GetSessionResponseSessionTypeSigning string = "signing"
)

// prop value enum
func (m *GetSessionResponse) validateSessionTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getSessionResponseTypeSessionTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GetSessionResponse) validateSessionType(formats strfmt.Registry) error {
	if swag.IsZero(m.SessionType) { // not required
		return nil
	}

	// value enum
	if err := m.validateSessionTypeEnum("session_type", "body", m.SessionType); err != nil {
		return err
	}

	return nil
}

var getSessionResponseTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","running","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getSessionResponseTypeStatusPropEnum = append(getSessionResponseTypeStatusPropEnum, v)
	}
}

const (

	// GetSessionResponseStatusPending captures enum value "pending"
	GetSessionResponseStatusPending string = "pending"

	// GetSessionResponseStatusRunning captures enum value "running"
	GetSessionResponseStatusRunning string = "running"

	// GetSessionResponseStatusCompleted captures enum value "completed"
	GetSessionResponseStatusCompleted string = "completed"

	// GetSessionResponseStatusFailed captures enum value "failed"
	GetSessionResponseStatusFailed string = "failed"
)

// prop value enum
func (m *GetSessionResponse) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getSessionResponseTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *GetSessionResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

func (m *GetSessionResponse) validateWalletID(formats strfmt.Registry) error {

	if err := validate.Required("wallet_id", "body", m.WalletID); err != nil {
		return err
	}

	if err := validate.FormatOf("wallet_id", "body", "uuid", m.WalletID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this get session response based on the context it is used
func (m *GetSessionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateProgress(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetSessionResponse) contextValidateProgress(ctx context.Context, formats strfmt.Registry) error {

	if m.Progress != nil {
		if err := m.Progress.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("progress")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("progress")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetSessionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSessionResponse) UnmarshalBinary(b []byte) error {
	var res GetSessionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// GetSessionResponseProgress get session response progress
//
// swagger:model GetSessionResponseProgress
type GetSessionResponseProgress struct {

	// current round
	// Example: 1
	CurrentRound int64 `json:"current_round,omitempty"`

	// total rounds
	// Example: 6
	TotalRounds int64 `json:"total_rounds,omitempty"`
}

// Validate validates this get session response progress
func (m *GetSessionResponseProgress) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get session response progress based on context it is used
func (m *GetSessionResponseProgress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetSessionResponseProgress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetSessionResponseProgress) UnmarshalBinary(b []byte) error {
	var res GetSessionResponseProgress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
