// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HeartbeatResponse heartbeat response
//
// swagger:model heartbeatResponse
type HeartbeatResponse struct {

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this heartbeat response
func (m *HeartbeatResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this heartbeat response based on context it is used
func (m *HeartbeatResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HeartbeatResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HeartbeatResponse) UnmarshalBinary(b []byte) error {
	var res HeartbeatResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
