// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ListBackupSharesResponse list backup shares response
//
// swagger:model listBackupSharesResponse
type ListBackupSharesResponse struct {

	// key id
	KeyID string `json:"key_id,omitempty"`

	// shares by node
	SharesByNode map[string]BackupShares `json:"shares_by_node,omitempty"`
}

// Validate validates this list backup shares response
func (m *ListBackupSharesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSharesByNode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListBackupSharesResponse) validateSharesByNode(formats strfmt.Registry) error {
	if swag.IsZero(m.SharesByNode) { // not required
		return nil
	}

	for k := range m.SharesByNode {

		if err := validate.Required("shares_by_node"+"."+k, "body", m.SharesByNode[k]); err != nil {
			return err
		}
		if val, ok := m.SharesByNode[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("shares_by_node" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("shares_by_node" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this list backup shares response based on the context it is used
func (m *ListBackupSharesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSharesByNode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListBackupSharesResponse) contextValidateSharesByNode(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.SharesByNode {

		if val, ok := m.SharesByNode[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListBackupSharesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListBackupSharesResponse) UnmarshalBinary(b []byte) error {
	var res ListBackupSharesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
