// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ListWalletsResponse list wallets response
//
// swagger:model listWalletsResponse
type ListWalletsResponse struct {

	// 每页数量
	// Required: true
	Limit *int64 `json:"limit"`

	// 偏移量
	// Required: true
	Offset *int64 `json:"offset"`

	// 总数
	// Required: true
	Total *int64 `json:"total"`

	// wallets
	// Required: true
	Wallets []*WalletSummary `json:"wallets"`
}

// Validate validates this list wallets response
func (m *ListWalletsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOffset(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWallets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListWalletsResponse) validateLimit(formats strfmt.Registry) error {

	if err := validate.Required("limit", "body", m.Limit); err != nil {
		return err
	}

	return nil
}

func (m *ListWalletsResponse) validateOffset(formats strfmt.Registry) error {

	if err := validate.Required("offset", "body", m.Offset); err != nil {
		return err
	}

	return nil
}

func (m *ListWalletsResponse) validateTotal(formats strfmt.Registry) error {

	if err := validate.Required("total", "body", m.Total); err != nil {
		return err
	}

	return nil
}

func (m *ListWalletsResponse) validateWallets(formats strfmt.Registry) error {

	if err := validate.Required("wallets", "body", m.Wallets); err != nil {
		return err
	}

	for i := 0; i < len(m.Wallets); i++ {
		if swag.IsZero(m.Wallets[i]) { // not required
			continue
		}

		if m.Wallets[i] != nil {
			if err := m.Wallets[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("wallets" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("wallets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this list wallets response based on the context it is used
func (m *ListWalletsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWallets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListWalletsResponse) contextValidateWallets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Wallets); i++ {

		if m.Wallets[i] != nil {
			if err := m.Wallets[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("wallets" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("wallets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListWalletsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListWalletsResponse) UnmarshalBinary(b []byte) error {
	var res ListWalletsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
