// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NodeRegistrationResponse node registration response
//
// swagger:model nodeRegistrationResponse
type NodeRegistrationResponse struct {

	// node id
	NodeID string `json:"node_id,omitempty"`

	// registered at
	// Format: date-time
	RegisteredAt strfmt.DateTime `json:"registered_at,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this node registration response
func (m *NodeRegistrationResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRegisteredAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NodeRegistrationResponse) validateRegisteredAt(formats strfmt.Registry) error {
	if swag.IsZero(m.RegisteredAt) { // not required
		return nil
	}

	if err := validate.FormatOf("registered_at", "body", "date-time", m.RegisteredAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this node registration response based on context it is used
func (m *NodeRegistrationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NodeRegistrationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodeRegistrationResponse) UnmarshalBinary(b []byte) error {
	var res NodeRegistrationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
