// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCreateWalletPayload post create wallet payload
//
// swagger:model postCreateWalletPayload
type PostCreateWalletPayload struct {

	// 签名算法
	// Example: ECDSA
	// Required: true
	// Enum: [ECDSA EdDSA]
	Algorithm *string `json:"algorithm"`

	// 区块链类型
	// Example: ethereum
	// Required: true
	// Enum: [ethereum bitcoin solana polkadot]
	ChainType *string `json:"chain_type"`

	// 椭圆曲线
	// Example: secp256k1
	// Required: true
	// Enum: [secp256k1 ed25519]
	Curve *string `json:"curve"`

	// webauthn assertion
	// Required: true
	WebauthnAssertion *WebAuthnAssertion `json:"webauthn_assertion"`
}

// Validate validates this post create wallet payload
func (m *PostCreateWalletPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlgorithm(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurve(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWebauthnAssertion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postCreateWalletPayloadTypeAlgorithmPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ECDSA","EdDSA"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postCreateWalletPayloadTypeAlgorithmPropEnum = append(postCreateWalletPayloadTypeAlgorithmPropEnum, v)
	}
}

const (

	// PostCreateWalletPayloadAlgorithmECDSA captures enum value "ECDSA"
	PostCreateWalletPayloadAlgorithmECDSA string = "ECDSA"

	// PostCreateWalletPayloadAlgorithmEdDSA captures enum value "EdDSA"
	PostCreateWalletPayloadAlgorithmEdDSA string = "EdDSA"
)

// prop value enum
func (m *PostCreateWalletPayload) validateAlgorithmEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postCreateWalletPayloadTypeAlgorithmPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostCreateWalletPayload) validateAlgorithm(formats strfmt.Registry) error {

	if err := validate.Required("algorithm", "body", m.Algorithm); err != nil {
		return err
	}

	// value enum
	if err := m.validateAlgorithmEnum("algorithm", "body", *m.Algorithm); err != nil {
		return err
	}

	return nil
}

var postCreateWalletPayloadTypeChainTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ethereum","bitcoin","solana","polkadot"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postCreateWalletPayloadTypeChainTypePropEnum = append(postCreateWalletPayloadTypeChainTypePropEnum, v)
	}
}

const (

	// PostCreateWalletPayloadChainTypeEthereum captures enum value "ethereum"
	PostCreateWalletPayloadChainTypeEthereum string = "ethereum"

	// PostCreateWalletPayloadChainTypeBitcoin captures enum value "bitcoin"
	PostCreateWalletPayloadChainTypeBitcoin string = "bitcoin"

	// PostCreateWalletPayloadChainTypeSolana captures enum value "solana"
	PostCreateWalletPayloadChainTypeSolana string = "solana"

	// PostCreateWalletPayloadChainTypePolkadot captures enum value "polkadot"
	PostCreateWalletPayloadChainTypePolkadot string = "polkadot"
)

// prop value enum
func (m *PostCreateWalletPayload) validateChainTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postCreateWalletPayloadTypeChainTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostCreateWalletPayload) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	// value enum
	if err := m.validateChainTypeEnum("chain_type", "body", *m.ChainType); err != nil {
		return err
	}

	return nil
}

var postCreateWalletPayloadTypeCurvePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["secp256k1","ed25519"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postCreateWalletPayloadTypeCurvePropEnum = append(postCreateWalletPayloadTypeCurvePropEnum, v)
	}
}

const (

	// PostCreateWalletPayloadCurveSecp256k1 captures enum value "secp256k1"
	PostCreateWalletPayloadCurveSecp256k1 string = "secp256k1"

	// PostCreateWalletPayloadCurveEd25519 captures enum value "ed25519"
	PostCreateWalletPayloadCurveEd25519 string = "ed25519"
)

// prop value enum
func (m *PostCreateWalletPayload) validateCurveEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postCreateWalletPayloadTypeCurvePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostCreateWalletPayload) validateCurve(formats strfmt.Registry) error {

	if err := validate.Required("curve", "body", m.Curve); err != nil {
		return err
	}

	// value enum
	if err := m.validateCurveEnum("curve", "body", *m.Curve); err != nil {
		return err
	}

	return nil
}

func (m *PostCreateWalletPayload) validateWebauthnAssertion(formats strfmt.Registry) error {

	if err := validate.Required("webauthn_assertion", "body", m.WebauthnAssertion); err != nil {
		return err
	}

	if m.WebauthnAssertion != nil {
		if err := m.WebauthnAssertion.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("webauthn_assertion")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("webauthn_assertion")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post create wallet payload based on the context it is used
func (m *PostCreateWalletPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWebauthnAssertion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCreateWalletPayload) contextValidateWebauthnAssertion(ctx context.Context, formats strfmt.Registry) error {

	if m.WebauthnAssertion != nil {
		if err := m.WebauthnAssertion.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("webauthn_assertion")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("webauthn_assertion")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostCreateWalletPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCreateWalletPayload) UnmarshalBinary(b []byte) error {
	var res PostCreateWalletPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
