// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostGenerateWalletAddressPayload post generate wallet address payload
//
// swagger:model postGenerateWalletAddressPayload
type PostGenerateWalletAddressPayload struct {

	// 区块链类型
	// Example: ethereum
	// Required: true
	// Enum: [ethereum bitcoin solana polkadot]
	ChainType *string `json:"chain_type"`

	// BIP44 派生路径（可选）
	// Example: m/44'/60'/0'/0/0
	DerivationPath string `json:"derivation_path,omitempty"`
}

// Validate validates this post generate wallet address payload
func (m *PostGenerateWalletAddressPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postGenerateWalletAddressPayloadTypeChainTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ethereum","bitcoin","solana","polkadot"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postGenerateWalletAddressPayloadTypeChainTypePropEnum = append(postGenerateWalletAddressPayloadTypeChainTypePropEnum, v)
	}
}

const (

	// PostGenerateWalletAddressPayloadChainTypeEthereum captures enum value "ethereum"
	PostGenerateWalletAddressPayloadChainTypeEthereum string = "ethereum"

	// PostGenerateWalletAddressPayloadChainTypeBitcoin captures enum value "bitcoin"
	PostGenerateWalletAddressPayloadChainTypeBitcoin string = "bitcoin"

	// PostGenerateWalletAddressPayloadChainTypeSolana captures enum value "solana"
	PostGenerateWalletAddressPayloadChainTypeSolana string = "solana"

	// PostGenerateWalletAddressPayloadChainTypePolkadot captures enum value "polkadot"
	PostGenerateWalletAddressPayloadChainTypePolkadot string = "polkadot"
)

// prop value enum
func (m *PostGenerateWalletAddressPayload) validateChainTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postGenerateWalletAddressPayloadTypeChainTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostGenerateWalletAddressPayload) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	// value enum
	if err := m.validateChainTypeEnum("chain_type", "body", *m.ChainType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post generate wallet address payload based on context it is used
func (m *PostGenerateWalletAddressPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostGenerateWalletAddressPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostGenerateWalletAddressPayload) UnmarshalBinary(b []byte) error {
	var res PostGenerateWalletAddressPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
