// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostSignTransactionPayload post sign transaction payload
//
// swagger:model postSignTransactionPayload
type PostSignTransactionPayload struct {

	// chain type
	// Example: ethereum
	// Required: true
	// Enum: [ethereum bitcoin solana]
	ChainType *string `json:"chain_type"`

	// 派生路径（可选）
	// Example: m/44'/60'/0'/0/0
	DerivationPath string `json:"derivation_path,omitempty"`

	// 待签名的消息（hex）
	// Example: 0xf86c...
	// Required: true
	MessageHex *string `json:"message_hex"`

	// webauthn assertion
	// Required: true
	WebauthnAssertion *WebAuthnAssertion `json:"webauthn_assertion"`
}

// Validate validates this post sign transaction payload
func (m *PostSignTransactionPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessageHex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWebauthnAssertion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postSignTransactionPayloadTypeChainTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ethereum","bitcoin","solana"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postSignTransactionPayloadTypeChainTypePropEnum = append(postSignTransactionPayloadTypeChainTypePropEnum, v)
	}
}

const (

	// PostSignTransactionPayloadChainTypeEthereum captures enum value "ethereum"
	PostSignTransactionPayloadChainTypeEthereum string = "ethereum"

	// PostSignTransactionPayloadChainTypeBitcoin captures enum value "bitcoin"
	PostSignTransactionPayloadChainTypeBitcoin string = "bitcoin"

	// PostSignTransactionPayloadChainTypeSolana captures enum value "solana"
	PostSignTransactionPayloadChainTypeSolana string = "solana"
)

// prop value enum
func (m *PostSignTransactionPayload) validateChainTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postSignTransactionPayloadTypeChainTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostSignTransactionPayload) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	// value enum
	if err := m.validateChainTypeEnum("chain_type", "body", *m.ChainType); err != nil {
		return err
	}

	return nil
}

func (m *PostSignTransactionPayload) validateMessageHex(formats strfmt.Registry) error {

	if err := validate.Required("message_hex", "body", m.MessageHex); err != nil {
		return err
	}

	return nil
}

func (m *PostSignTransactionPayload) validateWebauthnAssertion(formats strfmt.Registry) error {

	if err := validate.Required("webauthn_assertion", "body", m.WebauthnAssertion); err != nil {
		return err
	}

	if m.WebauthnAssertion != nil {
		if err := m.WebauthnAssertion.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("webauthn_assertion")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("webauthn_assertion")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post sign transaction payload based on the context it is used
func (m *PostSignTransactionPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWebauthnAssertion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostSignTransactionPayload) contextValidateWebauthnAssertion(ctx context.Context, formats strfmt.Registry) error {

	if m.WebauthnAssertion != nil {
		if err := m.WebauthnAssertion.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("webauthn_assertion")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("webauthn_assertion")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostSignTransactionPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostSignTransactionPayload) UnmarshalBinary(b []byte) error {
	var res PostSignTransactionPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
