// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostDeriveKeyPayload post derive key payload
//
// swagger:model postDeriveKeyPayload
type PostDeriveKeyPayload struct {

	// chain type
	// Example: ethereum
	// Required: true
	// Enum: [bitcoin ethereum bsc avalanche solana]
	ChainType *string `json:"chain_type"`

	// description
	// Example: 派生子钱包
	Description string `json:"description,omitempty"`

	// index
	// Example: 0
	// Required: true
	Index *int64 `json:"index"`

	// root key id
	// Example: key-1234567890abcdef
	// Required: true
	RootKeyID *string `json:"root_key_id"`

	// tags
	// Example: {"environment":"production"}
	Tags map[string]string `json:"tags,omitempty"`
}

// Validate validates this post derive key payload
func (m *PostDeriveKeyPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIndex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRootKeyID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postDeriveKeyPayloadTypeChainTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["bitcoin","ethereum","bsc","avalanche","solana"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postDeriveKeyPayloadTypeChainTypePropEnum = append(postDeriveKeyPayloadTypeChainTypePropEnum, v)
	}
}

const (

	// PostDeriveKeyPayloadChainTypeBitcoin captures enum value "bitcoin"
	PostDeriveKeyPayloadChainTypeBitcoin string = "bitcoin"

	// PostDeriveKeyPayloadChainTypeEthereum captures enum value "ethereum"
	PostDeriveKeyPayloadChainTypeEthereum string = "ethereum"

	// PostDeriveKeyPayloadChainTypeBsc captures enum value "bsc"
	PostDeriveKeyPayloadChainTypeBsc string = "bsc"

	// PostDeriveKeyPayloadChainTypeAvalanche captures enum value "avalanche"
	PostDeriveKeyPayloadChainTypeAvalanche string = "avalanche"

	// PostDeriveKeyPayloadChainTypeSolana captures enum value "solana"
	PostDeriveKeyPayloadChainTypeSolana string = "solana"
)

// prop value enum
func (m *PostDeriveKeyPayload) validateChainTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postDeriveKeyPayloadTypeChainTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PostDeriveKeyPayload) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	// value enum
	if err := m.validateChainTypeEnum("chain_type", "body", *m.ChainType); err != nil {
		return err
	}

	return nil
}

func (m *PostDeriveKeyPayload) validateIndex(formats strfmt.Registry) error {

	if err := validate.Required("index", "body", m.Index); err != nil {
		return err
	}

	return nil
}

func (m *PostDeriveKeyPayload) validateRootKeyID(formats strfmt.Registry) error {

	if err := validate.Required("root_key_id", "body", m.RootKeyID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post derive key payload based on context it is used
func (m *PostDeriveKeyPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostDeriveKeyPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostDeriveKeyPayload) UnmarshalBinary(b []byte) error {
	var res PostDeriveKeyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
