// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RecoverMPCShareResponse recover m p c share response
//
// swagger:model recoverMPCShareResponse
type RecoverMPCShareResponse struct {

	// key id
	KeyID string `json:"key_id,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// node id
	NodeID string `json:"node_id,omitempty"`

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this recover m p c share response
func (m *RecoverMPCShareResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this recover m p c share response based on context it is used
func (m *RecoverMPCShareResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RecoverMPCShareResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecoverMPCShareResponse) UnmarshalBinary(b []byte) error {
	var res RecoverMPCShareResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
