// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RecoverMPCShareRequest recover m p c share request
//
// swagger:model recoverMPCShareRequest
type RecoverMPCShareRequest struct {

	// key id
	KeyID string `json:"key_id,omitempty"`

	// node id
	NodeID string `json:"node_id,omitempty"`

	// Base64 encoded share data provided by the user
	// Format: byte
	ShareData strfmt.Base64 `json:"share_data,omitempty"`
}

// Validate validates this recover m p c share request
func (m *RecoverMPCShareRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this recover m p c share request based on context it is used
func (m *RecoverMPCShareRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RecoverMPCShareRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecoverMPCShareRequest) UnmarshalBinary(b []byte) error {
	var res RecoverMPCShareRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
