// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SessionResponse session response
//
// swagger:model sessionResponse
type SessionResponse struct {
	GetSessionResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SessionResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 GetSessionResponse
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.GetSessionResponse = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SessionResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.GetSessionResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this session response
func (m *SessionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this session response based on the context it is used
func (m *SessionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with GetSessionResponse
	if err := m.GetSessionResponse.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
