// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SignTransactionResponse sign transaction response
//
// swagger:model signTransactionResponse
type SignTransactionResponse struct {

	// 预计完成时间
	// Example: 2s
	EstimatedTime string `json:"estimated_time,omitempty"`

	// 签名会话 ID
	// Required: true
	// Format: uuid
	SessionID *strfmt.UUID `json:"session_id"`

	// 用于连接 Signer 的鉴权 Token
	SessionToken string `json:"session_token,omitempty"`

	// Signer 节点 gRPC 地址列表
	// Example: ["192.168.1.100:9091"]
	SignerEndpoints []string `json:"signer_endpoints"`

	// status
	// Example: pending
	// Required: true
	// Enum: [pending signing completed failed]
	Status *string `json:"status"`
}

// Validate validates this sign transaction response
func (m *SignTransactionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSessionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SignTransactionResponse) validateSessionID(formats strfmt.Registry) error {

	if err := validate.Required("session_id", "body", m.SessionID); err != nil {
		return err
	}

	if err := validate.FormatOf("session_id", "body", "uuid", m.SessionID.String(), formats); err != nil {
		return err
	}

	return nil
}

var signTransactionResponseTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","signing","completed","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		signTransactionResponseTypeStatusPropEnum = append(signTransactionResponseTypeStatusPropEnum, v)
	}
}

const (

	// SignTransactionResponseStatusPending captures enum value "pending"
	SignTransactionResponseStatusPending string = "pending"

	// SignTransactionResponseStatusSigning captures enum value "signing"
	SignTransactionResponseStatusSigning string = "signing"

	// SignTransactionResponseStatusCompleted captures enum value "completed"
	SignTransactionResponseStatusCompleted string = "completed"

	// SignTransactionResponseStatusFailed captures enum value "failed"
	SignTransactionResponseStatusFailed string = "failed"
)

// prop value enum
func (m *SignTransactionResponse) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, signTransactionResponseTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SignTransactionResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sign transaction response based on context it is used
func (m *SignTransactionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SignTransactionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignTransactionResponse) UnmarshalBinary(b []byte) error {
	var res SignTransactionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
