// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WalletSummary wallet summary
//
// swagger:model walletSummary
type WalletSummary struct {

	// address
	// Example: 0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb
	Address string `json:"address,omitempty"`

	// algorithm
	// Example: ECDSA
	Algorithm string `json:"algorithm,omitempty"`

	// chain type
	// Example: ethereum
	ChainType string `json:"chain_type,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// curve
	// Example: secp256k1
	Curve string `json:"curve,omitempty"`

	// public key
	// Example: 0x04...
	PublicKey string `json:"public_key,omitempty"`

	// wallet id
	// Format: uuid
	WalletID strfmt.UUID `json:"wallet_id,omitempty"`
}

// Validate validates this wallet summary
func (m *WalletSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWalletID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WalletSummary) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WalletSummary) validateWalletID(formats strfmt.Registry) error {
	if swag.IsZero(m.WalletID) { // not required
		return nil
	}

	if err := validate.FormatOf("wallet_id", "body", "uuid", m.WalletID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this wallet summary based on context it is used
func (m *WalletSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WalletSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WalletSummary) UnmarshalBinary(b []byte) error {
	var res WalletSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
