// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WalletBalanceResponse wallet balance response
//
// swagger:model walletBalanceResponse
type WalletBalanceResponse struct {

	// 余额（字符串，避免精度损失）
	// Example: 1.5
	// Required: true
	Balance *string `json:"balance"`

	// chain type
	// Example: ethereum
	ChainType string `json:"chain_type,omitempty"`

	// decimals
	// Example: 18
	// Required: true
	Decimals *int64 `json:"decimals"`

	// symbol
	// Example: ETH
	// Required: true
	Symbol *string `json:"symbol"`
}

// Validate validates this wallet balance response
func (m *WalletBalanceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBalance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDecimals(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSymbol(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WalletBalanceResponse) validateBalance(formats strfmt.Registry) error {

	if err := validate.Required("balance", "body", m.Balance); err != nil {
		return err
	}

	return nil
}

func (m *WalletBalanceResponse) validateDecimals(formats strfmt.Registry) error {

	if err := validate.Required("decimals", "body", m.Decimals); err != nil {
		return err
	}

	return nil
}

func (m *WalletBalanceResponse) validateSymbol(formats strfmt.Registry) error {

	if err := validate.Required("symbol", "body", m.Symbol); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this wallet balance response based on context it is used
func (m *WalletBalanceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WalletBalanceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WalletBalanceResponse) UnmarshalBinary(b []byte) error {
	var res WalletBalanceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
