// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WalletResponse wallet response
//
// swagger:model walletResponse
type WalletResponse struct {

	// address
	// Example: 0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb
	// Required: true
	Address *string `json:"address"`

	// algorithm
	// Example: ECDSA
	Algorithm string `json:"algorithm,omitempty"`

	// chain type
	// Example: ethereum
	// Required: true
	ChainType *string `json:"chain_type"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// curve
	// Example: secp256k1
	Curve string `json:"curve,omitempty"`

	// 公钥（hex）
	// Example: 0x04...
	// Required: true
	PublicKey *string `json:"public_key"`

	// threshold
	// Example: 2
	Threshold int64 `json:"threshold,omitempty"`

	// total nodes
	// Example: 2
	TotalNodes int64 `json:"total_nodes,omitempty"`

	// wallet id
	// Required: true
	// Format: uuid
	WalletID *strfmt.UUID `json:"wallet_id"`
}

// Validate validates this wallet response
func (m *WalletResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWalletID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WalletResponse) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *WalletResponse) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	return nil
}

func (m *WalletResponse) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WalletResponse) validatePublicKey(formats strfmt.Registry) error {

	if err := validate.Required("public_key", "body", m.PublicKey); err != nil {
		return err
	}

	return nil
}

func (m *WalletResponse) validateWalletID(formats strfmt.Registry) error {

	if err := validate.Required("wallet_id", "body", m.WalletID); err != nil {
		return err
	}

	if err := validate.FormatOf("wallet_id", "body", "uuid", m.WalletID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this wallet response based on context it is used
func (m *WalletResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WalletResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WalletResponse) UnmarshalBinary(b []byte) error {
	var res WalletResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
