// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WebAuthnAssertion web authn assertion
//
// swagger:model webAuthnAssertion
type WebAuthnAssertion struct {

	// Authenticator Data (base64)
	// Required: true
	// Format: byte
	AuthenticatorData *strfmt.Base64 `json:"authenticator_data"`

	// Client Data JSON (base64)
	// Required: true
	// Format: byte
	ClientDataJSON *strfmt.Base64 `json:"client_data_json"`

	// WebAuthn Credential ID (base64)
	// Example: Y3JlZGVudGlhbC1pZA==
	// Required: true
	// Format: byte
	CredentialID *strfmt.Base64 `json:"credential_id"`

	// Signature (base64)
	// Required: true
	// Format: byte
	Signature *strfmt.Base64 `json:"signature"`
}

// Validate validates this web authn assertion
func (m *WebAuthnAssertion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthenticatorData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateClientDataJSON(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCredentialID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WebAuthnAssertion) validateAuthenticatorData(formats strfmt.Registry) error {

	if err := validate.Required("authenticator_data", "body", m.AuthenticatorData); err != nil {
		return err
	}

	return nil
}

func (m *WebAuthnAssertion) validateClientDataJSON(formats strfmt.Registry) error {

	if err := validate.Required("client_data_json", "body", m.ClientDataJSON); err != nil {
		return err
	}

	return nil
}

func (m *WebAuthnAssertion) validateCredentialID(formats strfmt.Registry) error {

	if err := validate.Required("credential_id", "body", m.CredentialID); err != nil {
		return err
	}

	return nil
}

func (m *WebAuthnAssertion) validateSignature(formats strfmt.Registry) error {

	if err := validate.Required("signature", "body", m.Signature); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this web authn assertion based on context it is used
func (m *WebAuthnAssertion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WebAuthnAssertion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WebAuthnAssertion) UnmarshalBinary(b []byte) error {
	var res WebAuthnAssertion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
