// Code generated by go-swagger; DO NOT EDIT.

package wallets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetWalletTransactionsParams creates a new GetWalletTransactionsParams object
// with the default values initialized.
func NewGetWalletTransactionsParams() GetWalletTransactionsParams {

	var (
		// initialize parameters with default values

		limitDefault  = int64(20)
		offsetDefault = int64(0)
	)

	return GetWalletTransactionsParams{
		Limit: &limitDefault,

		Offset: &offsetDefault,
	}
}

// GetWalletTransactionsParams contains all the bound params for the get wallet transactions operation
// typically these are obtained from a http.Request
//
// swagger:parameters getWalletTransactions
type GetWalletTransactionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*区块链类型
	  Required: true
	  In: query
	*/
	ChainType string `query:"chain_type"`
	/*每页数量
	  In: query
	  Default: 20
	*/
	Limit *int64 `query:"limit"`
	/*偏移量
	  In: query
	  Default: 0
	*/
	Offset *int64 `query:"offset"`
	/*
	  Required: true
	  In: path
	*/
	WalletID string `param:"walletId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetWalletTransactionsParams() beforehand.
func (o *GetWalletTransactionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qChainType, qhkChainType, _ := qs.GetOK("chain_type")
	if err := o.bindChainType(qChainType, qhkChainType, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qOffset, qhkOffset, _ := qs.GetOK("offset")
	if err := o.bindOffset(qOffset, qhkOffset, route.Formats); err != nil {
		res = append(res, err)
	}

	rWalletID, rhkWalletID, _ := route.Params.GetOK("walletId")
	if err := o.bindWalletID(rWalletID, rhkWalletID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWalletTransactionsParams) Validate(formats strfmt.Registry) error {
	var res []error

	// chain_type
	// Required: true
	// AllowEmptyValue: false
	if err := validate.Required("chain_type", "query", o.ChainType); err != nil {
		res = append(res, err)
	}

	// limit
	// Required: false
	// AllowEmptyValue: false

	// offset
	// Required: false
	// AllowEmptyValue: false

	// walletId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChainType binds and validates parameter ChainType from query.
func (o *GetWalletTransactionsParams) bindChainType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("chain_type", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("chain_type", "query", raw); err != nil {
		return err
	}

	o.ChainType = raw

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetWalletTransactionsParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetWalletTransactionsParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int64", raw)
	}
	o.Limit = &value

	return nil
}

// bindOffset binds and validates parameter Offset from query.
func (o *GetWalletTransactionsParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetWalletTransactionsParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("offset", "query", "int64", raw)
	}
	o.Offset = &value

	return nil
}

// bindWalletID binds and validates parameter WalletID from path.
func (o *GetWalletTransactionsParams) bindWalletID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.WalletID = raw

	return nil
}
