// Code generated by go-swagger; DO NOT EDIT.

package wallets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetWalletBalanceParams creates a new GetWalletBalanceParams object
// no default values defined in spec.
func NewGetWalletBalanceParams() GetWalletBalanceParams {

	return GetWalletBalanceParams{}
}

// GetWalletBalanceParams contains all the bound params for the get wallet balance operation
// typically these are obtained from a http.Request
//
// swagger:parameters getWalletBalance
type GetWalletBalanceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*区块链类型
	  Required: true
	  In: query
	*/
	ChainType string `query:"chain_type"`
	/*
	  Required: true
	  In: path
	*/
	WalletID string `param:"walletId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetWalletBalanceParams() beforehand.
func (o *GetWalletBalanceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qChainType, qhkChainType, _ := qs.GetOK("chain_type")
	if err := o.bindChainType(qChainType, qhkChainType, route.Formats); err != nil {
		res = append(res, err)
	}

	rWalletID, rhkWalletID, _ := route.Params.GetOK("walletId")
	if err := o.bindWalletID(rWalletID, rhkWalletID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWalletBalanceParams) Validate(formats strfmt.Registry) error {
	var res []error

	// chain_type
	// Required: true
	// AllowEmptyValue: false
	if err := validate.Required("chain_type", "query", o.ChainType); err != nil {
		res = append(res, err)
	}

	// walletId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChainType binds and validates parameter ChainType from query.
func (o *GetWalletBalanceParams) bindChainType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("chain_type", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("chain_type", "query", raw); err != nil {
		return err
	}

	o.ChainType = raw

	return nil
}

// bindWalletID binds and validates parameter WalletID from path.
func (o *GetWalletBalanceParams) bindWalletID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.WalletID = raw

	return nil
}
