// Code generated by go-swagger; DO NOT EDIT.

package wallets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetWalletParams creates a new GetWalletParams object
// no default values defined in spec.
func NewGetWalletParams() GetWalletParams {

	return GetWalletParams{}
}

// GetWalletParams contains all the bound params for the get wallet operation
// typically these are obtained from a http.Request
//
// swagger:parameters getWallet
type GetWalletParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*钱包 ID
	  Required: true
	  In: path
	*/
	WalletID string `param:"walletId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetWalletParams() beforehand.
func (o *GetWalletParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rWalletID, rhkWalletID, _ := route.Params.GetOK("walletId")
	if err := o.bindWalletID(rWalletID, rhkWalletID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWalletParams) Validate(formats strfmt.Registry) error {
	var res []error

	// walletId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindWalletID binds and validates parameter WalletID from path.
func (o *GetWalletParams) bindWalletID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.WalletID = raw

	return nil
}
