// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// BackupShareDelivery is an object representing the database table.
type BackupShareDelivery struct {
	ID            int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	KeyID         string      `boil:"key_id" json:"key_id" toml:"key_id" yaml:"key_id"`
	NodeID        string      `boil:"node_id" json:"node_id" toml:"node_id" yaml:"node_id"`
	UserID        string      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	ShareIndex    int         `boil:"share_index" json:"share_index" toml:"share_index" yaml:"share_index"`
	Status        string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	DeliveredAt   null.Time   `boil:"delivered_at" json:"delivered_at,omitempty" toml:"delivered_at" yaml:"delivered_at,omitempty"`
	ConfirmedAt   null.Time   `boil:"confirmed_at" json:"confirmed_at,omitempty" toml:"confirmed_at" yaml:"confirmed_at,omitempty"`
	FailureReason null.String `boil:"failure_reason" json:"failure_reason,omitempty" toml:"failure_reason" yaml:"failure_reason,omitempty"`
	CreatedAt     time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *backupShareDeliveryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L backupShareDeliveryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BackupShareDeliveryColumns = struct {
	ID            string
	KeyID         string
	NodeID        string
	UserID        string
	ShareIndex    string
	Status        string
	DeliveredAt   string
	ConfirmedAt   string
	FailureReason string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	KeyID:         "key_id",
	NodeID:        "node_id",
	UserID:        "user_id",
	ShareIndex:    "share_index",
	Status:        "status",
	DeliveredAt:   "delivered_at",
	ConfirmedAt:   "confirmed_at",
	FailureReason: "failure_reason",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var BackupShareDeliveryTableColumns = struct {
	ID            string
	KeyID         string
	NodeID        string
	UserID        string
	ShareIndex    string
	Status        string
	DeliveredAt   string
	ConfirmedAt   string
	FailureReason string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "backup_share_deliveries.id",
	KeyID:         "backup_share_deliveries.key_id",
	NodeID:        "backup_share_deliveries.node_id",
	UserID:        "backup_share_deliveries.user_id",
	ShareIndex:    "backup_share_deliveries.share_index",
	Status:        "backup_share_deliveries.status",
	DeliveredAt:   "backup_share_deliveries.delivered_at",
	ConfirmedAt:   "backup_share_deliveries.confirmed_at",
	FailureReason: "backup_share_deliveries.failure_reason",
	CreatedAt:     "backup_share_deliveries.created_at",
	UpdatedAt:     "backup_share_deliveries.updated_at",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var BackupShareDeliveryWhere = struct {
	ID            whereHelperint64
	KeyID         whereHelperstring
	NodeID        whereHelperstring
	UserID        whereHelperstring
	ShareIndex    whereHelperint
	Status        whereHelperstring
	DeliveredAt   whereHelpernull_Time
	ConfirmedAt   whereHelpernull_Time
	FailureReason whereHelpernull_String
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
}{
	ID:            whereHelperint64{field: "\"backup_share_deliveries\".\"id\""},
	KeyID:         whereHelperstring{field: "\"backup_share_deliveries\".\"key_id\""},
	NodeID:        whereHelperstring{field: "\"backup_share_deliveries\".\"node_id\""},
	UserID:        whereHelperstring{field: "\"backup_share_deliveries\".\"user_id\""},
	ShareIndex:    whereHelperint{field: "\"backup_share_deliveries\".\"share_index\""},
	Status:        whereHelperstring{field: "\"backup_share_deliveries\".\"status\""},
	DeliveredAt:   whereHelpernull_Time{field: "\"backup_share_deliveries\".\"delivered_at\""},
	ConfirmedAt:   whereHelpernull_Time{field: "\"backup_share_deliveries\".\"confirmed_at\""},
	FailureReason: whereHelpernull_String{field: "\"backup_share_deliveries\".\"failure_reason\""},
	CreatedAt:     whereHelpertime_Time{field: "\"backup_share_deliveries\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"backup_share_deliveries\".\"updated_at\""},
}

// BackupShareDeliveryRels is where relationship names are stored.
var BackupShareDeliveryRels = struct {
	Key string
}{
	Key: "Key",
}

// backupShareDeliveryR is where relationships are stored.
type backupShareDeliveryR struct {
	Key *Key `boil:"Key" json:"Key" toml:"Key" yaml:"Key"`
}

// NewStruct creates a new relationship struct
func (*backupShareDeliveryR) NewStruct() *backupShareDeliveryR {
	return &backupShareDeliveryR{}
}

func (o *BackupShareDelivery) GetKey() *Key {
	if o == nil {
		return nil
	}

	return o.R.GetKey()
}

func (r *backupShareDeliveryR) GetKey() *Key {
	if r == nil {
		return nil
	}

	return r.Key
}

// backupShareDeliveryL is where Load methods for each relationship are stored.
type backupShareDeliveryL struct{}

var (
	backupShareDeliveryAllColumns            = []string{"id", "key_id", "node_id", "user_id", "share_index", "status", "delivered_at", "confirmed_at", "failure_reason", "created_at", "updated_at"}
	backupShareDeliveryColumnsWithoutDefault = []string{"key_id", "node_id", "user_id", "share_index", "status"}
	backupShareDeliveryColumnsWithDefault    = []string{"id", "delivered_at", "confirmed_at", "failure_reason", "created_at", "updated_at"}
	backupShareDeliveryPrimaryKeyColumns     = []string{"id"}
	backupShareDeliveryGeneratedColumns      = []string{}
)

type (
	// BackupShareDeliverySlice is an alias for a slice of pointers to BackupShareDelivery.
	// This should almost always be used instead of []BackupShareDelivery.
	BackupShareDeliverySlice []*BackupShareDelivery

	backupShareDeliveryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	backupShareDeliveryType                 = reflect.TypeOf(&BackupShareDelivery{})
	backupShareDeliveryMapping              = queries.MakeStructMapping(backupShareDeliveryType)
	backupShareDeliveryPrimaryKeyMapping, _ = queries.BindMapping(backupShareDeliveryType, backupShareDeliveryMapping, backupShareDeliveryPrimaryKeyColumns)
	backupShareDeliveryInsertCacheMut       sync.RWMutex
	backupShareDeliveryInsertCache          = make(map[string]insertCache)
	backupShareDeliveryUpdateCacheMut       sync.RWMutex
	backupShareDeliveryUpdateCache          = make(map[string]updateCache)
	backupShareDeliveryUpsertCacheMut       sync.RWMutex
	backupShareDeliveryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single backupShareDelivery record from the query.
func (q backupShareDeliveryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BackupShareDelivery, error) {
	o := &BackupShareDelivery{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for backup_share_deliveries")
	}

	return o, nil
}

// All returns all BackupShareDelivery records from the query.
func (q backupShareDeliveryQuery) All(ctx context.Context, exec boil.ContextExecutor) (BackupShareDeliverySlice, error) {
	var o []*BackupShareDelivery

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BackupShareDelivery slice")
	}

	return o, nil
}

// Count returns the count of all BackupShareDelivery records in the query.
func (q backupShareDeliveryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count backup_share_deliveries rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q backupShareDeliveryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if backup_share_deliveries exists")
	}

	return count > 0, nil
}

// Key pointed to by the foreign key.
func (o *BackupShareDelivery) Key(mods ...qm.QueryMod) keyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"key_id\" = ?", o.KeyID),
	}

	queryMods = append(queryMods, mods...)

	return Keys(queryMods...)
}

// LoadKey allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (backupShareDeliveryL) LoadKey(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBackupShareDelivery interface{}, mods queries.Applicator) error {
	var slice []*BackupShareDelivery
	var object *BackupShareDelivery

	if singular {
		var ok bool
		object, ok = maybeBackupShareDelivery.(*BackupShareDelivery)
		if !ok {
			object = new(BackupShareDelivery)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBackupShareDelivery)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBackupShareDelivery))
			}
		}
	} else {
		s, ok := maybeBackupShareDelivery.(*[]*BackupShareDelivery)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBackupShareDelivery)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBackupShareDelivery))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &backupShareDeliveryR{}
		}
		args[object.KeyID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &backupShareDeliveryR{}
			}

			args[obj.KeyID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`keys`),
		qm.WhereIn(`keys.key_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Key")
	}

	var resultSlice []*Key
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Key")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for keys")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for keys")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Key = foreign
		if foreign.R == nil {
			foreign.R = &keyR{}
		}
		foreign.R.BackupShareDeliveries = append(foreign.R.BackupShareDeliveries, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.KeyID == foreign.KeyID {
				local.R.Key = foreign
				if foreign.R == nil {
					foreign.R = &keyR{}
				}
				foreign.R.BackupShareDeliveries = append(foreign.R.BackupShareDeliveries, local)
				break
			}
		}
	}

	return nil
}

// SetKey of the backupShareDelivery to the related item.
// Sets o.R.Key to related.
// Adds o to related.R.BackupShareDeliveries.
func (o *BackupShareDelivery) SetKey(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Key) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"backup_share_deliveries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"key_id"}),
		strmangle.WhereClause("\"", "\"", 2, backupShareDeliveryPrimaryKeyColumns),
	)
	values := []interface{}{related.KeyID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.KeyID = related.KeyID
	if o.R == nil {
		o.R = &backupShareDeliveryR{
			Key: related,
		}
	} else {
		o.R.Key = related
	}

	if related.R == nil {
		related.R = &keyR{
			BackupShareDeliveries: BackupShareDeliverySlice{o},
		}
	} else {
		related.R.BackupShareDeliveries = append(related.R.BackupShareDeliveries, o)
	}

	return nil
}

// BackupShareDeliveries retrieves all the records using an executor.
func BackupShareDeliveries(mods ...qm.QueryMod) backupShareDeliveryQuery {
	mods = append(mods, qm.From("\"backup_share_deliveries\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"backup_share_deliveries\".*"})
	}

	return backupShareDeliveryQuery{q}
}

// FindBackupShareDelivery retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBackupShareDelivery(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*BackupShareDelivery, error) {
	backupShareDeliveryObj := &BackupShareDelivery{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"backup_share_deliveries\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, backupShareDeliveryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from backup_share_deliveries")
	}

	return backupShareDeliveryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BackupShareDelivery) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no backup_share_deliveries provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(backupShareDeliveryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	backupShareDeliveryInsertCacheMut.RLock()
	cache, cached := backupShareDeliveryInsertCache[key]
	backupShareDeliveryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			backupShareDeliveryAllColumns,
			backupShareDeliveryColumnsWithDefault,
			backupShareDeliveryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(backupShareDeliveryType, backupShareDeliveryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(backupShareDeliveryType, backupShareDeliveryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"backup_share_deliveries\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"backup_share_deliveries\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into backup_share_deliveries")
	}

	if !cached {
		backupShareDeliveryInsertCacheMut.Lock()
		backupShareDeliveryInsertCache[key] = cache
		backupShareDeliveryInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the BackupShareDelivery.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BackupShareDelivery) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	backupShareDeliveryUpdateCacheMut.RLock()
	cache, cached := backupShareDeliveryUpdateCache[key]
	backupShareDeliveryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			backupShareDeliveryAllColumns,
			backupShareDeliveryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update backup_share_deliveries, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"backup_share_deliveries\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, backupShareDeliveryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(backupShareDeliveryType, backupShareDeliveryMapping, append(wl, backupShareDeliveryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update backup_share_deliveries row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for backup_share_deliveries")
	}

	if !cached {
		backupShareDeliveryUpdateCacheMut.Lock()
		backupShareDeliveryUpdateCache[key] = cache
		backupShareDeliveryUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q backupShareDeliveryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for backup_share_deliveries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for backup_share_deliveries")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BackupShareDeliverySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), backupShareDeliveryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"backup_share_deliveries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, backupShareDeliveryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in backupShareDelivery slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all backupShareDelivery")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BackupShareDelivery) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no backup_share_deliveries provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(backupShareDeliveryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	backupShareDeliveryUpsertCacheMut.RLock()
	cache, cached := backupShareDeliveryUpsertCache[key]
	backupShareDeliveryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			backupShareDeliveryAllColumns,
			backupShareDeliveryColumnsWithDefault,
			backupShareDeliveryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			backupShareDeliveryAllColumns,
			backupShareDeliveryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert backup_share_deliveries, could not build update column list")
		}

		ret := strmangle.SetComplement(backupShareDeliveryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(backupShareDeliveryPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert backup_share_deliveries, could not build conflict column list")
			}

			conflict = make([]string, len(backupShareDeliveryPrimaryKeyColumns))
			copy(conflict, backupShareDeliveryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"backup_share_deliveries\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(backupShareDeliveryType, backupShareDeliveryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(backupShareDeliveryType, backupShareDeliveryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert backup_share_deliveries")
	}

	if !cached {
		backupShareDeliveryUpsertCacheMut.Lock()
		backupShareDeliveryUpsertCache[key] = cache
		backupShareDeliveryUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single BackupShareDelivery record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BackupShareDelivery) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no BackupShareDelivery provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), backupShareDeliveryPrimaryKeyMapping)
	sql := "DELETE FROM \"backup_share_deliveries\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from backup_share_deliveries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for backup_share_deliveries")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q backupShareDeliveryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no backupShareDeliveryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from backup_share_deliveries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for backup_share_deliveries")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BackupShareDeliverySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), backupShareDeliveryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"backup_share_deliveries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, backupShareDeliveryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from backupShareDelivery slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for backup_share_deliveries")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BackupShareDelivery) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBackupShareDelivery(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BackupShareDeliverySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BackupShareDeliverySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), backupShareDeliveryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"backup_share_deliveries\".* FROM \"backup_share_deliveries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, backupShareDeliveryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BackupShareDeliverySlice")
	}

	*o = slice

	return nil
}

// BackupShareDeliveryExists checks if the BackupShareDelivery row exists.
func BackupShareDeliveryExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"backup_share_deliveries\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if backup_share_deliveries exists")
	}

	return exists, nil
}

// Exists checks if the BackupShareDelivery row exists.
func (o *BackupShareDelivery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BackupShareDeliveryExists(ctx, exec, o.ID)
}
