// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// BackupShare is an object representing the database table.
type BackupShare struct {
	ID         int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	KeyID      string    `boil:"key_id" json:"key_id" toml:"key_id" yaml:"key_id"`
	NodeID     string    `boil:"node_id" json:"node_id" toml:"node_id" yaml:"node_id"`
	ShareIndex int       `boil:"share_index" json:"share_index" toml:"share_index" yaml:"share_index"`
	ShareData  []byte    `boil:"share_data" json:"share_data" toml:"share_data" yaml:"share_data"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *backupShareR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L backupShareL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BackupShareColumns = struct {
	ID         string
	KeyID      string
	NodeID     string
	ShareIndex string
	ShareData  string
	CreatedAt  string
}{
	ID:         "id",
	KeyID:      "key_id",
	NodeID:     "node_id",
	ShareIndex: "share_index",
	ShareData:  "share_data",
	CreatedAt:  "created_at",
}

var BackupShareTableColumns = struct {
	ID         string
	KeyID      string
	NodeID     string
	ShareIndex string
	ShareData  string
	CreatedAt  string
}{
	ID:         "backup_shares.id",
	KeyID:      "backup_shares.key_id",
	NodeID:     "backup_shares.node_id",
	ShareIndex: "backup_shares.share_index",
	ShareData:  "backup_shares.share_data",
	CreatedAt:  "backup_shares.created_at",
}

// Generated where

type whereHelper__byte struct{ field string }

func (w whereHelper__byte) EQ(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelper__byte) NEQ(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelper__byte) LT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelper__byte) LTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelper__byte) GT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelper__byte) GTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var BackupShareWhere = struct {
	ID         whereHelperint64
	KeyID      whereHelperstring
	NodeID     whereHelperstring
	ShareIndex whereHelperint
	ShareData  whereHelper__byte
	CreatedAt  whereHelpertime_Time
}{
	ID:         whereHelperint64{field: "\"backup_shares\".\"id\""},
	KeyID:      whereHelperstring{field: "\"backup_shares\".\"key_id\""},
	NodeID:     whereHelperstring{field: "\"backup_shares\".\"node_id\""},
	ShareIndex: whereHelperint{field: "\"backup_shares\".\"share_index\""},
	ShareData:  whereHelper__byte{field: "\"backup_shares\".\"share_data\""},
	CreatedAt:  whereHelpertime_Time{field: "\"backup_shares\".\"created_at\""},
}

// BackupShareRels is where relationship names are stored.
var BackupShareRels = struct {
	Key string
}{
	Key: "Key",
}

// backupShareR is where relationships are stored.
type backupShareR struct {
	Key *Key `boil:"Key" json:"Key" toml:"Key" yaml:"Key"`
}

// NewStruct creates a new relationship struct
func (*backupShareR) NewStruct() *backupShareR {
	return &backupShareR{}
}

func (o *BackupShare) GetKey() *Key {
	if o == nil {
		return nil
	}

	return o.R.GetKey()
}

func (r *backupShareR) GetKey() *Key {
	if r == nil {
		return nil
	}

	return r.Key
}

// backupShareL is where Load methods for each relationship are stored.
type backupShareL struct{}

var (
	backupShareAllColumns            = []string{"id", "key_id", "node_id", "share_index", "share_data", "created_at"}
	backupShareColumnsWithoutDefault = []string{"key_id", "node_id", "share_index", "share_data"}
	backupShareColumnsWithDefault    = []string{"id", "created_at"}
	backupSharePrimaryKeyColumns     = []string{"id"}
	backupShareGeneratedColumns      = []string{}
)

type (
	// BackupShareSlice is an alias for a slice of pointers to BackupShare.
	// This should almost always be used instead of []BackupShare.
	BackupShareSlice []*BackupShare

	backupShareQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	backupShareType                 = reflect.TypeOf(&BackupShare{})
	backupShareMapping              = queries.MakeStructMapping(backupShareType)
	backupSharePrimaryKeyMapping, _ = queries.BindMapping(backupShareType, backupShareMapping, backupSharePrimaryKeyColumns)
	backupShareInsertCacheMut       sync.RWMutex
	backupShareInsertCache          = make(map[string]insertCache)
	backupShareUpdateCacheMut       sync.RWMutex
	backupShareUpdateCache          = make(map[string]updateCache)
	backupShareUpsertCacheMut       sync.RWMutex
	backupShareUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single backupShare record from the query.
func (q backupShareQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BackupShare, error) {
	o := &BackupShare{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for backup_shares")
	}

	return o, nil
}

// All returns all BackupShare records from the query.
func (q backupShareQuery) All(ctx context.Context, exec boil.ContextExecutor) (BackupShareSlice, error) {
	var o []*BackupShare

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to BackupShare slice")
	}

	return o, nil
}

// Count returns the count of all BackupShare records in the query.
func (q backupShareQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count backup_shares rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q backupShareQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if backup_shares exists")
	}

	return count > 0, nil
}

// Key pointed to by the foreign key.
func (o *BackupShare) Key(mods ...qm.QueryMod) keyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"key_id\" = ?", o.KeyID),
	}

	queryMods = append(queryMods, mods...)

	return Keys(queryMods...)
}

// LoadKey allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (backupShareL) LoadKey(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBackupShare interface{}, mods queries.Applicator) error {
	var slice []*BackupShare
	var object *BackupShare

	if singular {
		var ok bool
		object, ok = maybeBackupShare.(*BackupShare)
		if !ok {
			object = new(BackupShare)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBackupShare)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBackupShare))
			}
		}
	} else {
		s, ok := maybeBackupShare.(*[]*BackupShare)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBackupShare)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBackupShare))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &backupShareR{}
		}
		args[object.KeyID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &backupShareR{}
			}

			args[obj.KeyID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`keys`),
		qm.WhereIn(`keys.key_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Key")
	}

	var resultSlice []*Key
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Key")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for keys")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for keys")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Key = foreign
		if foreign.R == nil {
			foreign.R = &keyR{}
		}
		foreign.R.BackupShares = append(foreign.R.BackupShares, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.KeyID == foreign.KeyID {
				local.R.Key = foreign
				if foreign.R == nil {
					foreign.R = &keyR{}
				}
				foreign.R.BackupShares = append(foreign.R.BackupShares, local)
				break
			}
		}
	}

	return nil
}

// SetKey of the backupShare to the related item.
// Sets o.R.Key to related.
// Adds o to related.R.BackupShares.
func (o *BackupShare) SetKey(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Key) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"backup_shares\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"key_id"}),
		strmangle.WhereClause("\"", "\"", 2, backupSharePrimaryKeyColumns),
	)
	values := []interface{}{related.KeyID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.KeyID = related.KeyID
	if o.R == nil {
		o.R = &backupShareR{
			Key: related,
		}
	} else {
		o.R.Key = related
	}

	if related.R == nil {
		related.R = &keyR{
			BackupShares: BackupShareSlice{o},
		}
	} else {
		related.R.BackupShares = append(related.R.BackupShares, o)
	}

	return nil
}

// BackupShares retrieves all the records using an executor.
func BackupShares(mods ...qm.QueryMod) backupShareQuery {
	mods = append(mods, qm.From("\"backup_shares\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"backup_shares\".*"})
	}

	return backupShareQuery{q}
}

// FindBackupShare retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBackupShare(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*BackupShare, error) {
	backupShareObj := &BackupShare{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"backup_shares\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, backupShareObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from backup_shares")
	}

	return backupShareObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BackupShare) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no backup_shares provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(backupShareColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	backupShareInsertCacheMut.RLock()
	cache, cached := backupShareInsertCache[key]
	backupShareInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			backupShareAllColumns,
			backupShareColumnsWithDefault,
			backupShareColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(backupShareType, backupShareMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(backupShareType, backupShareMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"backup_shares\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"backup_shares\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into backup_shares")
	}

	if !cached {
		backupShareInsertCacheMut.Lock()
		backupShareInsertCache[key] = cache
		backupShareInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the BackupShare.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BackupShare) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	backupShareUpdateCacheMut.RLock()
	cache, cached := backupShareUpdateCache[key]
	backupShareUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			backupShareAllColumns,
			backupSharePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update backup_shares, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"backup_shares\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, backupSharePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(backupShareType, backupShareMapping, append(wl, backupSharePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update backup_shares row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for backup_shares")
	}

	if !cached {
		backupShareUpdateCacheMut.Lock()
		backupShareUpdateCache[key] = cache
		backupShareUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q backupShareQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for backup_shares")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for backup_shares")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BackupShareSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), backupSharePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"backup_shares\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, backupSharePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in backupShare slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all backupShare")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BackupShare) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no backup_shares provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(backupShareColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	backupShareUpsertCacheMut.RLock()
	cache, cached := backupShareUpsertCache[key]
	backupShareUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			backupShareAllColumns,
			backupShareColumnsWithDefault,
			backupShareColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			backupShareAllColumns,
			backupSharePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert backup_shares, could not build update column list")
		}

		ret := strmangle.SetComplement(backupShareAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(backupSharePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert backup_shares, could not build conflict column list")
			}

			conflict = make([]string, len(backupSharePrimaryKeyColumns))
			copy(conflict, backupSharePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"backup_shares\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(backupShareType, backupShareMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(backupShareType, backupShareMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert backup_shares")
	}

	if !cached {
		backupShareUpsertCacheMut.Lock()
		backupShareUpsertCache[key] = cache
		backupShareUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single BackupShare record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BackupShare) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no BackupShare provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), backupSharePrimaryKeyMapping)
	sql := "DELETE FROM \"backup_shares\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from backup_shares")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for backup_shares")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q backupShareQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no backupShareQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from backup_shares")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for backup_shares")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BackupShareSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), backupSharePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"backup_shares\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, backupSharePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from backupShare slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for backup_shares")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BackupShare) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBackupShare(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BackupShareSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BackupShareSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), backupSharePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"backup_shares\".* FROM \"backup_shares\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, backupSharePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BackupShareSlice")
	}

	*o = slice

	return nil
}

// BackupShareExists checks if the BackupShare row exists.
func BackupShareExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"backup_shares\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if backup_shares exists")
	}

	return exists, nil
}

// Exists checks if the BackupShare row exists.
func (o *BackupShare) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BackupShareExists(ctx, exec, o.ID)
}
