// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccessTokens          string
	AppUserProfiles       string
	AuditLogs             string
	BackupShareDeliveries string
	BackupShares          string
	ConfirmationTokens    string
	Keys                  string
	Nodes                 string
	Passkeys              string
	PasswordResetTokens   string
	PushTokens            string
	RefreshTokens         string
	SigningPolicies       string
	SigningSessions       string
	Users                 string
}{
	AccessTokens:          "access_tokens",
	AppUserProfiles:       "app_user_profiles",
	AuditLogs:             "audit_logs",
	BackupShareDeliveries: "backup_share_deliveries",
	BackupShares:          "backup_shares",
	ConfirmationTokens:    "confirmation_tokens",
	Keys:                  "keys",
	Nodes:                 "nodes",
	Passkeys:              "passkeys",
	PasswordResetTokens:   "password_reset_tokens",
	PushTokens:            "push_tokens",
	RefreshTokens:         "refresh_tokens",
	SigningPolicies:       "signing_policies",
	SigningSessions:       "signing_sessions",
	Users:                 "users",
}
