// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPasskeys(t *testing.T) {
	t.Parallel()

	query := Passkeys()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPasskeysDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Passkeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPasskeysQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Passkeys().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Passkeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPasskeysSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PasskeySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Passkeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPasskeysExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PasskeyExists(ctx, tx, o.CredentialID)
	if err != nil {
		t.Errorf("Unable to check if Passkey exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PasskeyExists to return true, but got false.")
	}
}

func testPasskeysFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	passkeyFound, err := FindPasskey(ctx, tx, o.CredentialID)
	if err != nil {
		t.Error(err)
	}

	if passkeyFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPasskeysBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Passkeys().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPasskeysOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Passkeys().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPasskeysAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	passkeyOne := &Passkey{}
	passkeyTwo := &Passkey{}
	if err = randomize.Struct(seed, passkeyOne, passkeyDBTypes, false, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}
	if err = randomize.Struct(seed, passkeyTwo, passkeyDBTypes, false, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = passkeyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = passkeyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Passkeys().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPasskeysCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	passkeyOne := &Passkey{}
	passkeyTwo := &Passkey{}
	if err = randomize.Struct(seed, passkeyOne, passkeyDBTypes, false, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}
	if err = randomize.Struct(seed, passkeyTwo, passkeyDBTypes, false, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = passkeyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = passkeyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Passkeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testPasskeysInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Passkeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPasskeysInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(passkeyPrimaryKeyColumns, passkeyColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Passkeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPasskeysReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPasskeysReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PasskeySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPasskeysSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Passkeys().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	passkeyDBTypes = map[string]string{`CredentialID`: `character varying`, `PublicKey`: `text`, `DeviceName`: `character varying`, `CreatedAt`: `timestamp with time zone`}
	_              = bytes.MinRead
)

func testPasskeysUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(passkeyPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(passkeyAllColumns) == len(passkeyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Passkeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPasskeysSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(passkeyAllColumns) == len(passkeyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Passkey{}
	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Passkeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, passkeyDBTypes, true, passkeyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(passkeyAllColumns, passkeyPrimaryKeyColumns) {
		fields = passkeyAllColumns
	} else {
		fields = strmangle.SetComplement(
			passkeyAllColumns,
			passkeyPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PasskeySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPasskeysUpsert(t *testing.T) {
	t.Parallel()

	if len(passkeyAllColumns) == len(passkeyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Passkey{}
	if err = randomize.Struct(seed, &o, passkeyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Passkey: %s", err)
	}

	count, err := Passkeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, passkeyDBTypes, false, passkeyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Passkey struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Passkey: %s", err)
	}

	count, err = Passkeys().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
