// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// SigningPolicy is an object representing the database table.
type SigningPolicy struct {
	WalletID      string    `boil:"wallet_id" json:"wallet_id" toml:"wallet_id" yaml:"wallet_id"`
	PolicyType    string    `boil:"policy_type" json:"policy_type" toml:"policy_type" yaml:"policy_type"`
	MinSignatures int       `boil:"min_signatures" json:"min_signatures" toml:"min_signatures" yaml:"min_signatures"`
	CreatedAt     null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt     null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *signingPolicyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L signingPolicyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SigningPolicyColumns = struct {
	WalletID      string
	PolicyType    string
	MinSignatures string
	CreatedAt     string
	UpdatedAt     string
}{
	WalletID:      "wallet_id",
	PolicyType:    "policy_type",
	MinSignatures: "min_signatures",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var SigningPolicyTableColumns = struct {
	WalletID      string
	PolicyType    string
	MinSignatures string
	CreatedAt     string
	UpdatedAt     string
}{
	WalletID:      "signing_policies.wallet_id",
	PolicyType:    "signing_policies.policy_type",
	MinSignatures: "signing_policies.min_signatures",
	CreatedAt:     "signing_policies.created_at",
	UpdatedAt:     "signing_policies.updated_at",
}

// Generated where

var SigningPolicyWhere = struct {
	WalletID      whereHelperstring
	PolicyType    whereHelperstring
	MinSignatures whereHelperint
	CreatedAt     whereHelpernull_Time
	UpdatedAt     whereHelpernull_Time
}{
	WalletID:      whereHelperstring{field: "\"signing_policies\".\"wallet_id\""},
	PolicyType:    whereHelperstring{field: "\"signing_policies\".\"policy_type\""},
	MinSignatures: whereHelperint{field: "\"signing_policies\".\"min_signatures\""},
	CreatedAt:     whereHelpernull_Time{field: "\"signing_policies\".\"created_at\""},
	UpdatedAt:     whereHelpernull_Time{field: "\"signing_policies\".\"updated_at\""},
}

// SigningPolicyRels is where relationship names are stored.
var SigningPolicyRels = struct {
}{}

// signingPolicyR is where relationships are stored.
type signingPolicyR struct {
}

// NewStruct creates a new relationship struct
func (*signingPolicyR) NewStruct() *signingPolicyR {
	return &signingPolicyR{}
}

// signingPolicyL is where Load methods for each relationship are stored.
type signingPolicyL struct{}

var (
	signingPolicyAllColumns            = []string{"wallet_id", "policy_type", "min_signatures", "created_at", "updated_at"}
	signingPolicyColumnsWithoutDefault = []string{"wallet_id", "policy_type", "min_signatures"}
	signingPolicyColumnsWithDefault    = []string{"created_at", "updated_at"}
	signingPolicyPrimaryKeyColumns     = []string{"wallet_id"}
	signingPolicyGeneratedColumns      = []string{}
)

type (
	// SigningPolicySlice is an alias for a slice of pointers to SigningPolicy.
	// This should almost always be used instead of []SigningPolicy.
	SigningPolicySlice []*SigningPolicy

	signingPolicyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	signingPolicyType                 = reflect.TypeOf(&SigningPolicy{})
	signingPolicyMapping              = queries.MakeStructMapping(signingPolicyType)
	signingPolicyPrimaryKeyMapping, _ = queries.BindMapping(signingPolicyType, signingPolicyMapping, signingPolicyPrimaryKeyColumns)
	signingPolicyInsertCacheMut       sync.RWMutex
	signingPolicyInsertCache          = make(map[string]insertCache)
	signingPolicyUpdateCacheMut       sync.RWMutex
	signingPolicyUpdateCache          = make(map[string]updateCache)
	signingPolicyUpsertCacheMut       sync.RWMutex
	signingPolicyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single signingPolicy record from the query.
func (q signingPolicyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SigningPolicy, error) {
	o := &SigningPolicy{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for signing_policies")
	}

	return o, nil
}

// All returns all SigningPolicy records from the query.
func (q signingPolicyQuery) All(ctx context.Context, exec boil.ContextExecutor) (SigningPolicySlice, error) {
	var o []*SigningPolicy

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SigningPolicy slice")
	}

	return o, nil
}

// Count returns the count of all SigningPolicy records in the query.
func (q signingPolicyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count signing_policies rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q signingPolicyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if signing_policies exists")
	}

	return count > 0, nil
}

// SigningPolicies retrieves all the records using an executor.
func SigningPolicies(mods ...qm.QueryMod) signingPolicyQuery {
	mods = append(mods, qm.From("\"signing_policies\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"signing_policies\".*"})
	}

	return signingPolicyQuery{q}
}

// FindSigningPolicy retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSigningPolicy(ctx context.Context, exec boil.ContextExecutor, walletID string, selectCols ...string) (*SigningPolicy, error) {
	signingPolicyObj := &SigningPolicy{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"signing_policies\" where \"wallet_id\"=$1", sel,
	)

	q := queries.Raw(query, walletID)

	err := q.Bind(ctx, exec, signingPolicyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from signing_policies")
	}

	return signingPolicyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SigningPolicy) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no signing_policies provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(signingPolicyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	signingPolicyInsertCacheMut.RLock()
	cache, cached := signingPolicyInsertCache[key]
	signingPolicyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			signingPolicyAllColumns,
			signingPolicyColumnsWithDefault,
			signingPolicyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(signingPolicyType, signingPolicyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(signingPolicyType, signingPolicyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"signing_policies\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"signing_policies\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into signing_policies")
	}

	if !cached {
		signingPolicyInsertCacheMut.Lock()
		signingPolicyInsertCache[key] = cache
		signingPolicyInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the SigningPolicy.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SigningPolicy) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	key := makeCacheKey(columns, nil)
	signingPolicyUpdateCacheMut.RLock()
	cache, cached := signingPolicyUpdateCache[key]
	signingPolicyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			signingPolicyAllColumns,
			signingPolicyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update signing_policies, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"signing_policies\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, signingPolicyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(signingPolicyType, signingPolicyMapping, append(wl, signingPolicyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update signing_policies row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for signing_policies")
	}

	if !cached {
		signingPolicyUpdateCacheMut.Lock()
		signingPolicyUpdateCache[key] = cache
		signingPolicyUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q signingPolicyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for signing_policies")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for signing_policies")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SigningPolicySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), signingPolicyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"signing_policies\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, signingPolicyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in signingPolicy slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all signingPolicy")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SigningPolicy) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no signing_policies provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	nzDefaults := queries.NonZeroDefaultSet(signingPolicyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	signingPolicyUpsertCacheMut.RLock()
	cache, cached := signingPolicyUpsertCache[key]
	signingPolicyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			signingPolicyAllColumns,
			signingPolicyColumnsWithDefault,
			signingPolicyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			signingPolicyAllColumns,
			signingPolicyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert signing_policies, could not build update column list")
		}

		ret := strmangle.SetComplement(signingPolicyAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(signingPolicyPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert signing_policies, could not build conflict column list")
			}

			conflict = make([]string, len(signingPolicyPrimaryKeyColumns))
			copy(conflict, signingPolicyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"signing_policies\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(signingPolicyType, signingPolicyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(signingPolicyType, signingPolicyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert signing_policies")
	}

	if !cached {
		signingPolicyUpsertCacheMut.Lock()
		signingPolicyUpsertCache[key] = cache
		signingPolicyUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single SigningPolicy record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SigningPolicy) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no SigningPolicy provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), signingPolicyPrimaryKeyMapping)
	sql := "DELETE FROM \"signing_policies\" WHERE \"wallet_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from signing_policies")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for signing_policies")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q signingPolicyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no signingPolicyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from signing_policies")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for signing_policies")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SigningPolicySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), signingPolicyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"signing_policies\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, signingPolicyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from signingPolicy slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for signing_policies")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SigningPolicy) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSigningPolicy(ctx, exec, o.WalletID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SigningPolicySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SigningPolicySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), signingPolicyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"signing_policies\".* FROM \"signing_policies\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, signingPolicyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SigningPolicySlice")
	}

	*o = slice

	return nil
}

// SigningPolicyExists checks if the SigningPolicy row exists.
func SigningPolicyExists(ctx context.Context, exec boil.ContextExecutor, walletID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"signing_policies\" where \"wallet_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, walletID)
	}
	row := exec.QueryRowContext(ctx, sql, walletID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if signing_policies exists")
	}

	return exists, nil
}

// Exists checks if the SigningPolicy row exists.
func (o *SigningPolicy) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SigningPolicyExists(ctx, exec, o.WalletID)
}
