// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSigningPolicies(t *testing.T) {
	t.Parallel()

	query := SigningPolicies()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSigningPoliciesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SigningPolicies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSigningPoliciesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SigningPolicies().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SigningPolicies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSigningPoliciesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SigningPolicySlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SigningPolicies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSigningPoliciesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SigningPolicyExists(ctx, tx, o.WalletID)
	if err != nil {
		t.Errorf("Unable to check if SigningPolicy exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SigningPolicyExists to return true, but got false.")
	}
}

func testSigningPoliciesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	signingPolicyFound, err := FindSigningPolicy(ctx, tx, o.WalletID)
	if err != nil {
		t.Error(err)
	}

	if signingPolicyFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSigningPoliciesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SigningPolicies().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSigningPoliciesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SigningPolicies().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSigningPoliciesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	signingPolicyOne := &SigningPolicy{}
	signingPolicyTwo := &SigningPolicy{}
	if err = randomize.Struct(seed, signingPolicyOne, signingPolicyDBTypes, false, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}
	if err = randomize.Struct(seed, signingPolicyTwo, signingPolicyDBTypes, false, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = signingPolicyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = signingPolicyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SigningPolicies().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSigningPoliciesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	signingPolicyOne := &SigningPolicy{}
	signingPolicyTwo := &SigningPolicy{}
	if err = randomize.Struct(seed, signingPolicyOne, signingPolicyDBTypes, false, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}
	if err = randomize.Struct(seed, signingPolicyTwo, signingPolicyDBTypes, false, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = signingPolicyOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = signingPolicyTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningPolicies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testSigningPoliciesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningPolicies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSigningPoliciesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(signingPolicyPrimaryKeyColumns, signingPolicyColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := SigningPolicies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSigningPoliciesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSigningPoliciesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SigningPolicySlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSigningPoliciesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SigningPolicies().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	signingPolicyDBTypes = map[string]string{`WalletID`: `character varying`, `PolicyType`: `character varying`, `MinSignatures`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                    = bytes.MinRead
)

func testSigningPoliciesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(signingPolicyPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(signingPolicyAllColumns) == len(signingPolicyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningPolicies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSigningPoliciesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(signingPolicyAllColumns) == len(signingPolicyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SigningPolicy{}
	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningPolicies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, signingPolicyDBTypes, true, signingPolicyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(signingPolicyAllColumns, signingPolicyPrimaryKeyColumns) {
		fields = signingPolicyAllColumns
	} else {
		fields = strmangle.SetComplement(
			signingPolicyAllColumns,
			signingPolicyPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SigningPolicySlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSigningPoliciesUpsert(t *testing.T) {
	t.Parallel()

	if len(signingPolicyAllColumns) == len(signingPolicyPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SigningPolicy{}
	if err = randomize.Struct(seed, &o, signingPolicyDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SigningPolicy: %s", err)
	}

	count, err := SigningPolicies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, signingPolicyDBTypes, false, signingPolicyPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SigningPolicy struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SigningPolicy: %s", err)
	}

	count, err = SigningPolicies().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
