// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// UserAuthKey is an object representing the database table.
type UserAuthKey struct {
	ID           string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	WalletID     string      `boil:"wallet_id" json:"wallet_id" toml:"wallet_id" yaml:"wallet_id"`
	PublicKeyHex string      `boil:"public_key_hex" json:"public_key_hex" toml:"public_key_hex" yaml:"public_key_hex"`
	KeyType      string      `boil:"key_type" json:"key_type" toml:"key_type" yaml:"key_type"`
	MemberName   null.String `boil:"member_name" json:"member_name,omitempty" toml:"member_name" yaml:"member_name,omitempty"`
	Role         null.String `boil:"role" json:"role,omitempty" toml:"role" yaml:"role,omitempty"`
	CreatedAt    null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *userAuthKeyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userAuthKeyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserAuthKeyColumns = struct {
	ID           string
	WalletID     string
	PublicKeyHex string
	KeyType      string
	MemberName   string
	Role         string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	WalletID:     "wallet_id",
	PublicKeyHex: "public_key_hex",
	KeyType:      "key_type",
	MemberName:   "member_name",
	Role:         "role",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var UserAuthKeyTableColumns = struct {
	ID           string
	WalletID     string
	PublicKeyHex string
	KeyType      string
	MemberName   string
	Role         string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "user_auth_keys.id",
	WalletID:     "user_auth_keys.wallet_id",
	PublicKeyHex: "user_auth_keys.public_key_hex",
	KeyType:      "user_auth_keys.key_type",
	MemberName:   "user_auth_keys.member_name",
	Role:         "user_auth_keys.role",
	CreatedAt:    "user_auth_keys.created_at",
	UpdatedAt:    "user_auth_keys.updated_at",
}

// Generated where

var UserAuthKeyWhere = struct {
	ID           whereHelperstring
	WalletID     whereHelperstring
	PublicKeyHex whereHelperstring
	KeyType      whereHelperstring
	MemberName   whereHelpernull_String
	Role         whereHelpernull_String
	CreatedAt    whereHelpernull_Time
	UpdatedAt    whereHelpernull_Time
}{
	ID:           whereHelperstring{field: "\"user_auth_keys\".\"id\""},
	WalletID:     whereHelperstring{field: "\"user_auth_keys\".\"wallet_id\""},
	PublicKeyHex: whereHelperstring{field: "\"user_auth_keys\".\"public_key_hex\""},
	KeyType:      whereHelperstring{field: "\"user_auth_keys\".\"key_type\""},
	MemberName:   whereHelpernull_String{field: "\"user_auth_keys\".\"member_name\""},
	Role:         whereHelpernull_String{field: "\"user_auth_keys\".\"role\""},
	CreatedAt:    whereHelpernull_Time{field: "\"user_auth_keys\".\"created_at\""},
	UpdatedAt:    whereHelpernull_Time{field: "\"user_auth_keys\".\"updated_at\""},
}

// UserAuthKeyRels is where relationship names are stored.
var UserAuthKeyRels = struct {
}{}

// userAuthKeyR is where relationships are stored.
type userAuthKeyR struct {
}

// NewStruct creates a new relationship struct
func (*userAuthKeyR) NewStruct() *userAuthKeyR {
	return &userAuthKeyR{}
}

// userAuthKeyL is where Load methods for each relationship are stored.
type userAuthKeyL struct{}

var (
	userAuthKeyAllColumns            = []string{"id", "wallet_id", "public_key_hex", "key_type", "member_name", "role", "created_at", "updated_at"}
	userAuthKeyColumnsWithoutDefault = []string{"wallet_id", "public_key_hex", "key_type"}
	userAuthKeyColumnsWithDefault    = []string{"id", "member_name", "role", "created_at", "updated_at"}
	userAuthKeyPrimaryKeyColumns     = []string{"id"}
	userAuthKeyGeneratedColumns      = []string{}
)

type (
	// UserAuthKeySlice is an alias for a slice of pointers to UserAuthKey.
	// This should almost always be used instead of []UserAuthKey.
	UserAuthKeySlice []*UserAuthKey

	userAuthKeyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userAuthKeyType                 = reflect.TypeOf(&UserAuthKey{})
	userAuthKeyMapping              = queries.MakeStructMapping(userAuthKeyType)
	userAuthKeyPrimaryKeyMapping, _ = queries.BindMapping(userAuthKeyType, userAuthKeyMapping, userAuthKeyPrimaryKeyColumns)
	userAuthKeyInsertCacheMut       sync.RWMutex
	userAuthKeyInsertCache          = make(map[string]insertCache)
	userAuthKeyUpdateCacheMut       sync.RWMutex
	userAuthKeyUpdateCache          = make(map[string]updateCache)
	userAuthKeyUpsertCacheMut       sync.RWMutex
	userAuthKeyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single userAuthKey record from the query.
func (q userAuthKeyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserAuthKey, error) {
	o := &UserAuthKey{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_auth_keys")
	}

	return o, nil
}

// All returns all UserAuthKey records from the query.
func (q userAuthKeyQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserAuthKeySlice, error) {
	var o []*UserAuthKey

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserAuthKey slice")
	}

	return o, nil
}

// Count returns the count of all UserAuthKey records in the query.
func (q userAuthKeyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_auth_keys rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userAuthKeyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_auth_keys exists")
	}

	return count > 0, nil
}

// UserAuthKeys retrieves all the records using an executor.
func UserAuthKeys(mods ...qm.QueryMod) userAuthKeyQuery {
	mods = append(mods, qm.From("\"user_auth_keys\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_auth_keys\".*"})
	}

	return userAuthKeyQuery{q}
}

// FindUserAuthKey retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserAuthKey(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*UserAuthKey, error) {
	userAuthKeyObj := &UserAuthKey{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_auth_keys\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userAuthKeyObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_auth_keys")
	}

	return userAuthKeyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserAuthKey) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_auth_keys provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(userAuthKeyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userAuthKeyInsertCacheMut.RLock()
	cache, cached := userAuthKeyInsertCache[key]
	userAuthKeyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userAuthKeyAllColumns,
			userAuthKeyColumnsWithDefault,
			userAuthKeyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userAuthKeyType, userAuthKeyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userAuthKeyType, userAuthKeyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_auth_keys\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_auth_keys\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_auth_keys")
	}

	if !cached {
		userAuthKeyInsertCacheMut.Lock()
		userAuthKeyInsertCache[key] = cache
		userAuthKeyInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the UserAuthKey.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserAuthKey) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	key := makeCacheKey(columns, nil)
	userAuthKeyUpdateCacheMut.RLock()
	cache, cached := userAuthKeyUpdateCache[key]
	userAuthKeyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userAuthKeyAllColumns,
			userAuthKeyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update user_auth_keys, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_auth_keys\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userAuthKeyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userAuthKeyType, userAuthKeyMapping, append(wl, userAuthKeyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update user_auth_keys row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for user_auth_keys")
	}

	if !cached {
		userAuthKeyUpdateCacheMut.Lock()
		userAuthKeyUpdateCache[key] = cache
		userAuthKeyUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q userAuthKeyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for user_auth_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for user_auth_keys")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserAuthKeySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userAuthKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_auth_keys\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userAuthKeyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userAuthKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userAuthKey")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserAuthKey) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no user_auth_keys provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	nzDefaults := queries.NonZeroDefaultSet(userAuthKeyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userAuthKeyUpsertCacheMut.RLock()
	cache, cached := userAuthKeyUpsertCache[key]
	userAuthKeyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userAuthKeyAllColumns,
			userAuthKeyColumnsWithDefault,
			userAuthKeyColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userAuthKeyAllColumns,
			userAuthKeyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert user_auth_keys, could not build update column list")
		}

		ret := strmangle.SetComplement(userAuthKeyAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userAuthKeyPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert user_auth_keys, could not build conflict column list")
			}

			conflict = make([]string, len(userAuthKeyPrimaryKeyColumns))
			copy(conflict, userAuthKeyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_auth_keys\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userAuthKeyType, userAuthKeyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userAuthKeyType, userAuthKeyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert user_auth_keys")
	}

	if !cached {
		userAuthKeyUpsertCacheMut.Lock()
		userAuthKeyUpsertCache[key] = cache
		userAuthKeyUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single UserAuthKey record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserAuthKey) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserAuthKey provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userAuthKeyPrimaryKeyMapping)
	sql := "DELETE FROM \"user_auth_keys\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from user_auth_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for user_auth_keys")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userAuthKeyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userAuthKeyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from user_auth_keys")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_auth_keys")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserAuthKeySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userAuthKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_auth_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userAuthKeyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userAuthKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_auth_keys")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserAuthKey) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserAuthKey(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserAuthKeySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserAuthKeySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userAuthKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_auth_keys\".* FROM \"user_auth_keys\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userAuthKeyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserAuthKeySlice")
	}

	*o = slice

	return nil
}

// UserAuthKeyExists checks if the UserAuthKey row exists.
func UserAuthKeyExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_auth_keys\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_auth_keys exists")
	}

	return exists, nil
}

// Exists checks if the UserAuthKey row exists.
func (o *UserAuthKey) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserAuthKeyExists(ctx, exec, o.ID)
}
