// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: mpc/v1/mpc.proto

package mpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MPCNode_SubmitProtocolMessage_FullMethodName = "/mpc.v1.MPCNode/SubmitProtocolMessage"
	MPCNode_StartDKG_FullMethodName              = "/mpc.v1.MPCNode/StartDKG"
	MPCNode_StartSign_FullMethodName             = "/mpc.v1.MPCNode/StartSign"
	MPCNode_StartResharing_FullMethodName        = "/mpc.v1.MPCNode/StartResharing"
	MPCNode_Heartbeat_FullMethodName             = "/mpc.v1.MPCNode/Heartbeat"
)

// MPCNodeClient is the client API for MPCNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MPC核心服务定义
type MPCNodeClient interface {
	// 提交协议消息
	SubmitProtocolMessage(ctx context.Context, in *SubmitProtocolMessageRequest, opts ...grpc.CallOption) (*SubmitProtocolMessageResponse, error)
	// 启动 DKG（由协调者调用参与者）
	StartDKG(ctx context.Context, in *StartDKGRequest, opts ...grpc.CallOption) (*StartDKGResponse, error)
	// 启动签名（由协调者调用参与者）
	StartSign(ctx context.Context, in *StartSignRequest, opts ...grpc.CallOption) (*StartSignResponse, error)
	// 启动密钥轮换（Resharing）（由协调者调用参与者）
	StartResharing(ctx context.Context, in *StartResharingRequest, opts ...grpc.CallOption) (*StartResharingResponse, error)
	// 心跳检测
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type mPCNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCNodeClient(cc grpc.ClientConnInterface) MPCNodeClient {
	return &mPCNodeClient{cc}
}

func (c *mPCNodeClient) SubmitProtocolMessage(ctx context.Context, in *SubmitProtocolMessageRequest, opts ...grpc.CallOption) (*SubmitProtocolMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitProtocolMessageResponse)
	err := c.cc.Invoke(ctx, MPCNode_SubmitProtocolMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeClient) StartDKG(ctx context.Context, in *StartDKGRequest, opts ...grpc.CallOption) (*StartDKGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDKGResponse)
	err := c.cc.Invoke(ctx, MPCNode_StartDKG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeClient) StartSign(ctx context.Context, in *StartSignRequest, opts ...grpc.CallOption) (*StartSignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSignResponse)
	err := c.cc.Invoke(ctx, MPCNode_StartSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeClient) StartResharing(ctx context.Context, in *StartResharingRequest, opts ...grpc.CallOption) (*StartResharingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResharingResponse)
	err := c.cc.Invoke(ctx, MPCNode_StartResharing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MPCNode_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MPCNodeServer is the server API for MPCNode service.
// All implementations must embed UnimplementedMPCNodeServer
// for forward compatibility.
//
// MPC核心服务定义
type MPCNodeServer interface {
	// 提交协议消息
	SubmitProtocolMessage(context.Context, *SubmitProtocolMessageRequest) (*SubmitProtocolMessageResponse, error)
	// 启动 DKG（由协调者调用参与者）
	StartDKG(context.Context, *StartDKGRequest) (*StartDKGResponse, error)
	// 启动签名（由协调者调用参与者）
	StartSign(context.Context, *StartSignRequest) (*StartSignResponse, error)
	// 启动密钥轮换（Resharing）（由协调者调用参与者）
	StartResharing(context.Context, *StartResharingRequest) (*StartResharingResponse, error)
	// 心跳检测
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedMPCNodeServer()
}

// UnimplementedMPCNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPCNodeServer struct{}

func (UnimplementedMPCNodeServer) SubmitProtocolMessage(context.Context, *SubmitProtocolMessageRequest) (*SubmitProtocolMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitProtocolMessage not implemented")
}
func (UnimplementedMPCNodeServer) StartDKG(context.Context, *StartDKGRequest) (*StartDKGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDKG not implemented")
}
func (UnimplementedMPCNodeServer) StartSign(context.Context, *StartSignRequest) (*StartSignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSign not implemented")
}
func (UnimplementedMPCNodeServer) StartResharing(context.Context, *StartResharingRequest) (*StartResharingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartResharing not implemented")
}
func (UnimplementedMPCNodeServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMPCNodeServer) mustEmbedUnimplementedMPCNodeServer() {}
func (UnimplementedMPCNodeServer) testEmbeddedByValue()                 {}

// UnsafeMPCNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPCNodeServer will
// result in compilation errors.
type UnsafeMPCNodeServer interface {
	mustEmbedUnimplementedMPCNodeServer()
}

func RegisterMPCNodeServer(s grpc.ServiceRegistrar, srv MPCNodeServer) {
	// If the following call pancis, it indicates UnimplementedMPCNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPCNode_ServiceDesc, srv)
}

func _MPCNode_SubmitProtocolMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitProtocolMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServer).SubmitProtocolMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNode_SubmitProtocolMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServer).SubmitProtocolMessage(ctx, req.(*SubmitProtocolMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNode_StartDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDKGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServer).StartDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNode_StartDKG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServer).StartDKG(ctx, req.(*StartDKGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNode_StartSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServer).StartSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNode_StartSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServer).StartSign(ctx, req.(*StartSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNode_StartResharing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartResharingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServer).StartResharing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNode_StartResharing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServer).StartResharing(ctx, req.(*StartResharingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNode_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNode_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MPCNode_ServiceDesc is the grpc.ServiceDesc for MPCNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPCNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.v1.MPCNode",
	HandlerType: (*MPCNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitProtocolMessage",
			Handler:    _MPCNode_SubmitProtocolMessage_Handler,
		},
		{
			MethodName: "StartDKG",
			Handler:    _MPCNode_StartDKG_Handler,
		},
		{
			MethodName: "StartSign",
			Handler:    _MPCNode_StartSign_Handler,
		},
		{
			MethodName: "StartResharing",
			Handler:    _MPCNode_StartResharing_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _MPCNode_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpc/v1/mpc.proto",
}

const (
	MPCCoordinator_CreateSigningSession_FullMethodName = "/mpc.v1.MPCCoordinator/CreateSigningSession"
	MPCCoordinator_GetSessionStatus_FullMethodName     = "/mpc.v1.MPCCoordinator/GetSessionStatus"
	MPCCoordinator_AggregateSignatures_FullMethodName  = "/mpc.v1.MPCCoordinator/AggregateSignatures"
)

// MPCCoordinatorClient is the client API for MPCCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MPCCoordinatorClient interface {
	// 创建签名会话
	CreateSigningSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	// 获取会话状态
	GetSessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error)
	// 聚合签名
	AggregateSignatures(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error)
}

type mPCCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCCoordinatorClient(cc grpc.ClientConnInterface) MPCCoordinatorClient {
	return &mPCCoordinatorClient{cc}
}

func (c *mPCCoordinatorClient) CreateSigningSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, MPCCoordinator_CreateSigningSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCCoordinatorClient) GetSessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStatusResponse)
	err := c.cc.Invoke(ctx, MPCCoordinator_GetSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCCoordinatorClient) AggregateSignatures(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AggregateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregateResponse)
	err := c.cc.Invoke(ctx, MPCCoordinator_AggregateSignatures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MPCCoordinatorServer is the server API for MPCCoordinator service.
// All implementations must embed UnimplementedMPCCoordinatorServer
// for forward compatibility.
type MPCCoordinatorServer interface {
	// 创建签名会话
	CreateSigningSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	// 获取会话状态
	GetSessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error)
	// 聚合签名
	AggregateSignatures(context.Context, *AggregateRequest) (*AggregateResponse, error)
	mustEmbedUnimplementedMPCCoordinatorServer()
}

// UnimplementedMPCCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPCCoordinatorServer struct{}

func (UnimplementedMPCCoordinatorServer) CreateSigningSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSigningSession not implemented")
}
func (UnimplementedMPCCoordinatorServer) GetSessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionStatus not implemented")
}
func (UnimplementedMPCCoordinatorServer) AggregateSignatures(context.Context, *AggregateRequest) (*AggregateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateSignatures not implemented")
}
func (UnimplementedMPCCoordinatorServer) mustEmbedUnimplementedMPCCoordinatorServer() {}
func (UnimplementedMPCCoordinatorServer) testEmbeddedByValue()                        {}

// UnsafeMPCCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPCCoordinatorServer will
// result in compilation errors.
type UnsafeMPCCoordinatorServer interface {
	mustEmbedUnimplementedMPCCoordinatorServer()
}

func RegisterMPCCoordinatorServer(s grpc.ServiceRegistrar, srv MPCCoordinatorServer) {
	// If the following call pancis, it indicates UnimplementedMPCCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPCCoordinator_ServiceDesc, srv)
}

func _MPCCoordinator_CreateSigningSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCCoordinatorServer).CreateSigningSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCCoordinator_CreateSigningSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCCoordinatorServer).CreateSigningSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCCoordinator_GetSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCCoordinatorServer).GetSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCCoordinator_GetSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCCoordinatorServer).GetSessionStatus(ctx, req.(*SessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCCoordinator_AggregateSignatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCCoordinatorServer).AggregateSignatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCCoordinator_AggregateSignatures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCCoordinatorServer).AggregateSignatures(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MPCCoordinator_ServiceDesc is the grpc.ServiceDesc for MPCCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPCCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.v1.MPCCoordinator",
	HandlerType: (*MPCCoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSigningSession",
			Handler:    _MPCCoordinator_CreateSigningSession_Handler,
		},
		{
			MethodName: "GetSessionStatus",
			Handler:    _MPCCoordinator_GetSessionStatus_Handler,
		},
		{
			MethodName: "AggregateSignatures",
			Handler:    _MPCCoordinator_AggregateSignatures_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpc/v1/mpc.proto",
}

const (
	MPCManagement_SetSigningPolicy_FullMethodName   = "/mpc.v1.MPCManagement/SetSigningPolicy"
	MPCManagement_GetSigningPolicy_FullMethodName   = "/mpc.v1.MPCManagement/GetSigningPolicy"
	MPCManagement_AddPasskey_FullMethodName         = "/mpc.v1.MPCManagement/AddPasskey"
	MPCManagement_AddWalletMember_FullMethodName    = "/mpc.v1.MPCManagement/AddWalletMember"
	MPCManagement_RemoveWalletMember_FullMethodName = "/mpc.v1.MPCManagement/RemoveWalletMember"
)

// MPCManagementClient is the client API for MPCManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MPC管理服务
type MPCManagementClient interface {
	// 设置签名策略
	SetSigningPolicy(ctx context.Context, in *SetSigningPolicyRequest, opts ...grpc.CallOption) (*SetSigningPolicyResponse, error)
	// 获取签名策略
	GetSigningPolicy(ctx context.Context, in *GetSigningPolicyRequest, opts ...grpc.CallOption) (*GetSigningPolicyResponse, error)
	// 添加用户 Passkey 公钥
	AddPasskey(ctx context.Context, in *AddPasskeyRequest, opts ...grpc.CallOption) (*AddPasskeyResponse, error)
	// 钱包成员管理
	AddWalletMember(ctx context.Context, in *AddWalletMemberRequest, opts ...grpc.CallOption) (*AddWalletMemberResponse, error)
	RemoveWalletMember(ctx context.Context, in *RemoveWalletMemberRequest, opts ...grpc.CallOption) (*RemoveWalletMemberResponse, error)
}

type mPCManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCManagementClient(cc grpc.ClientConnInterface) MPCManagementClient {
	return &mPCManagementClient{cc}
}

func (c *mPCManagementClient) SetSigningPolicy(ctx context.Context, in *SetSigningPolicyRequest, opts ...grpc.CallOption) (*SetSigningPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSigningPolicyResponse)
	err := c.cc.Invoke(ctx, MPCManagement_SetSigningPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCManagementClient) GetSigningPolicy(ctx context.Context, in *GetSigningPolicyRequest, opts ...grpc.CallOption) (*GetSigningPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSigningPolicyResponse)
	err := c.cc.Invoke(ctx, MPCManagement_GetSigningPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCManagementClient) AddPasskey(ctx context.Context, in *AddPasskeyRequest, opts ...grpc.CallOption) (*AddPasskeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPasskeyResponse)
	err := c.cc.Invoke(ctx, MPCManagement_AddPasskey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCManagementClient) AddWalletMember(ctx context.Context, in *AddWalletMemberRequest, opts ...grpc.CallOption) (*AddWalletMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddWalletMemberResponse)
	err := c.cc.Invoke(ctx, MPCManagement_AddWalletMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCManagementClient) RemoveWalletMember(ctx context.Context, in *RemoveWalletMemberRequest, opts ...grpc.CallOption) (*RemoveWalletMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveWalletMemberResponse)
	err := c.cc.Invoke(ctx, MPCManagement_RemoveWalletMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MPCManagementServer is the server API for MPCManagement service.
// All implementations must embed UnimplementedMPCManagementServer
// for forward compatibility.
//
// MPC管理服务
type MPCManagementServer interface {
	// 设置签名策略
	SetSigningPolicy(context.Context, *SetSigningPolicyRequest) (*SetSigningPolicyResponse, error)
	// 获取签名策略
	GetSigningPolicy(context.Context, *GetSigningPolicyRequest) (*GetSigningPolicyResponse, error)
	// 添加用户 Passkey 公钥
	AddPasskey(context.Context, *AddPasskeyRequest) (*AddPasskeyResponse, error)
	// 钱包成员管理
	AddWalletMember(context.Context, *AddWalletMemberRequest) (*AddWalletMemberResponse, error)
	RemoveWalletMember(context.Context, *RemoveWalletMemberRequest) (*RemoveWalletMemberResponse, error)
	mustEmbedUnimplementedMPCManagementServer()
}

// UnimplementedMPCManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPCManagementServer struct{}

func (UnimplementedMPCManagementServer) SetSigningPolicy(context.Context, *SetSigningPolicyRequest) (*SetSigningPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSigningPolicy not implemented")
}
func (UnimplementedMPCManagementServer) GetSigningPolicy(context.Context, *GetSigningPolicyRequest) (*GetSigningPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSigningPolicy not implemented")
}
func (UnimplementedMPCManagementServer) AddPasskey(context.Context, *AddPasskeyRequest) (*AddPasskeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPasskey not implemented")
}
func (UnimplementedMPCManagementServer) AddWalletMember(context.Context, *AddWalletMemberRequest) (*AddWalletMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWalletMember not implemented")
}
func (UnimplementedMPCManagementServer) RemoveWalletMember(context.Context, *RemoveWalletMemberRequest) (*RemoveWalletMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWalletMember not implemented")
}
func (UnimplementedMPCManagementServer) mustEmbedUnimplementedMPCManagementServer() {}
func (UnimplementedMPCManagementServer) testEmbeddedByValue()                       {}

// UnsafeMPCManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPCManagementServer will
// result in compilation errors.
type UnsafeMPCManagementServer interface {
	mustEmbedUnimplementedMPCManagementServer()
}

func RegisterMPCManagementServer(s grpc.ServiceRegistrar, srv MPCManagementServer) {
	// If the following call pancis, it indicates UnimplementedMPCManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPCManagement_ServiceDesc, srv)
}

func _MPCManagement_SetSigningPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSigningPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCManagementServer).SetSigningPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCManagement_SetSigningPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCManagementServer).SetSigningPolicy(ctx, req.(*SetSigningPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCManagement_GetSigningPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSigningPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCManagementServer).GetSigningPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCManagement_GetSigningPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCManagementServer).GetSigningPolicy(ctx, req.(*GetSigningPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCManagement_AddPasskey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPasskeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCManagementServer).AddPasskey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCManagement_AddPasskey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCManagementServer).AddPasskey(ctx, req.(*AddPasskeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCManagement_AddWalletMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWalletMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCManagementServer).AddWalletMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCManagement_AddWalletMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCManagementServer).AddWalletMember(ctx, req.(*AddWalletMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCManagement_RemoveWalletMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWalletMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCManagementServer).RemoveWalletMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCManagement_RemoveWalletMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCManagementServer).RemoveWalletMember(ctx, req.(*RemoveWalletMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MPCManagement_ServiceDesc is the grpc.ServiceDesc for MPCManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPCManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.v1.MPCManagement",
	HandlerType: (*MPCManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetSigningPolicy",
			Handler:    _MPCManagement_SetSigningPolicy_Handler,
		},
		{
			MethodName: "GetSigningPolicy",
			Handler:    _MPCManagement_GetSigningPolicy_Handler,
		},
		{
			MethodName: "AddPasskey",
			Handler:    _MPCManagement_AddPasskey_Handler,
		},
		{
			MethodName: "AddWalletMember",
			Handler:    _MPCManagement_AddWalletMember_Handler,
		},
		{
			MethodName: "RemoveWalletMember",
			Handler:    _MPCManagement_RemoveWalletMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpc/v1/mpc.proto",
}
