// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetBackupStatusParams creates a new GetBackupStatusParams object
// no default values defined in spec.
func NewGetBackupStatusParams() GetBackupStatusParams {

	return GetBackupStatusParams{}
}

// GetBackupStatusParams contains all the bound params for the get backup status operation
// typically these are obtained from a http.Request
//
// swagger:parameters getBackupStatus
type GetBackupStatusParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: query
	*/
	KeyID string `query:"key_id"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetBackupStatusParams() beforehand.
func (o *GetBackupStatusParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qKeyID, qhkKeyID, _ := qs.GetOK("key_id")
	if err := o.bindKeyID(qKeyID, qhkKeyID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetBackupStatusParams) Validate(formats strfmt.Registry) error {
	var res []error

	// key_id
	// Required: true
	// AllowEmptyValue: false
	if err := validate.Required("key_id", "query", o.KeyID); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindKeyID binds and validates parameter KeyID from query.
func (o *GetBackupStatusParams) bindKeyID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("key_id", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("key_id", "query", raw); err != nil {
		return err
	}

	o.KeyID = raw

	return nil
}
