// Code generated by go run -tags scripts scripts/handlers/gen_handlers.go; DO NOT EDIT.
package handlers

import (
	"github.com/SafeMPC/mpc-service/internal/api"
	"github.com/SafeMPC/mpc-service/internal/api/handlers/auth"
	"github.com/SafeMPC/mpc-service/internal/api/handlers/common"
	"github.com/SafeMPC/mpc-service/internal/api/handlers/infra/sessions"
	"github.com/SafeMPC/mpc-service/internal/api/handlers/push"
	walletshandlers "github.com/SafeMPC/mpc-service/internal/api/handlers/wallets"
	webauthnhandlers "github.com/SafeMPC/mpc-service/internal/api/handlers/webauthn"
	websockethandlers "github.com/SafeMPC/mpc-service/internal/api/handlers/websocket"
	"github.com/SafeMPC/mpc-service/internal/api/handlers/wellknown"
	"github.com/labstack/echo/v4"
)

func AttachAllRoutes(s *api.Server) {
	// attach our routes
	s.Router.Routes = []*echo.Route{
		auth.DeleteUserAccountRoute(s),
		auth.GetCompleteRegisterRoute(s),
		auth.GetUserInfoRoute(s),
		auth.PostChangePasswordRoute(s),
		auth.PostCompleteRegisterRoute(s),
		auth.PostForgotPasswordCompleteRoute(s),
		auth.PostForgotPasswordRoute(s),
		auth.PostLoginRoute(s),
		auth.PostLogoutRoute(s),
		auth.PostRefreshRoute(s),
		auth.PostRegisterRoute(s),
		webauthnhandlers.PostWebAuthnRegisterBeginRoute(s),
		webauthnhandlers.PostWebAuthnRegisterFinishRoute(s),
		webauthnhandlers.PostWebAuthnLoginBeginRoute(s),
		webauthnhandlers.PostWebAuthnLoginFinishRoute(s),
		common.GetHealthyRoute(s),
		common.GetReadyRoute(s),
		common.GetSwaggerRoute(s),
		common.GetVersionRoute(s),
		sessions.GetSessionRoute(s),
		walletshandlers.PostCreateWalletRoute(s),
		walletshandlers.GetWalletsRoute(s),
		walletshandlers.GetWalletRoute(s),
		walletshandlers.GetWalletBalanceRoute(s),
		walletshandlers.PostSignTransactionRoute(s),
		websockethandlers.WebSocketRoute(s),
		push.PutUpdatePushTokenRoute(s),
		wellknown.GetAndroidDigitalAssetLinksRoute(s),
		wellknown.GetAppleAppSiteAssociationRoute(s),
	}
}
